project:
  type: website

website:
  title: "Nollatoleranssi-hankkeen liitesivusto"
  navbar:
    left:
      - href: index.qmd
        text: Etusivu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  cache: true

