project:
  type: book
  output-dir: docs

book:
  title: "Nollatoleranssi-hankkeen liitesivusto"
  author: "Oliver Saal"
  
  chapters:
    - index.qmd
    - part: "Kirjallisuuskatsaus"
      chapters:
        - kriteeristo.qmd
        - seulontamenetelma.qmd
        - hakuprosessi.qmd
        - yleiskuvailu.qmd
        - katsausartikkeli.qmd
    - part: "Katsauksen osahaut"
      chapters:
        - haku1.qmd
        - haku2.qmd
        - haku3.qmd
        - haku4.qmd
        - haku5.qmd
        - haku6.qmd
    - part: "Kyselyprosessi"
      chapters:
        - kyselynvalmistelu.qmd
        - tiedonkeruu.qmd
        - eksportointi.qmd
        - nimeaminen.qmd
        - valmistelu.qmd
        - puhdistaminen.qmd
        - anonymisointi.qmd
    - part: "Kyselyn tulokset"
      chapters:
        - datatarkistus.qmd
        - metatiedot.qmd
        - taustamuuttujat.qmd
        - esiintyvyys.qmd
        - vaikutukset.qmd
        - ilmoitusjarjestelmat.qmd
        - organisaatiotoimet.qmd
        - ryhmavertailut.qmd
        - korrelaatiosuhteet.qmd
    - part: "Mittaristojen validoinnit"
      chapters:
        - kohtelu_validointi.qmd
        - ilmoasenteet_validointi.qmd
        - tayvkayttoonotto_validointi.qmd
        - tayvasenteet_validointi.qmd
    - part: "Esitykset ja kirjoitukset"
      chapters:
        - deibseminaari.qmd
        - blogi1.qmd

    - lahteet.qmd
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Etusivu"
        file: index.qmd
      - sidebar:kirjallisuuskatsaus
      - sidebar:katsauksenhaut
      - sidebar:kyselyprosessi
      - sidebar:kyselyntulokset
      - sidebar:validointi
      - sidebar:esitykset
      - text: "Lähteet"
        file: lahteet.qmd
  
  sidebar:
    - id: kirjallisuuskatsaus
      title: "Kirjallisuuskatsaus"
      style: docked
      background: primary
      collapse-level: 2
      contents:
        - kriteeristo.qmd
        - seulontamenetelma.qmd
        - hakuprosessi.qmd
        - yleiskuvailu.qmd
        - katsausartikkeli.qmd
    
    - id: katsauksenhaut
      title: "Katsauksen osahaut"
      contents:
        - haku1.qmd
        - haku2.qmd
        - haku3.qmd
        - haku4.qmd
        - haku5.qmd
        - haku6.qmd
    
    - id: kyselyprosessi
      title: "Kyselyprosessi"
      contents:
        - kyselynvalmistelu.qmd
        - tiedonkeruu.qmd
        - eksportointi.qmd
        - nimeaminen.qmd
        - valmistelu.qmd
        - puhdistaminen.qmd
        - anonymisointi.qmd
    
    - id: kyselyntulokset
      title: "Kyselyn tulokset"
      contents:
        - datatarkistus.qmd
        - metatiedot.qmd
        - taustamuuttujat.qmd
        - esiintyvyys.qmd
        - vaikutukset.qmd
        - ilmoitusjarjestelmat.qmd
        - organisaatiotoimet.qmd
        - ryhmavertailut.qmd
        - korrelaatiosuhteet.qmd
    
    - id: validointi
      title: "Mittaristojen validoinnit"
      contents:
        - kohtelu_validointi.qmd
        - ilmoasenteet_validointi.qmd
        - tayvkayttoonotto_validointi.qmd
        - tayvasenteet_validointi.qmd
    
    - id: esitykset
      title: "Esitykset ja kirjoitukset"
      contents:
        - deibseminaari.qmd
        - blogi1.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    lang: fi
    crossref:
      chapters: true
    reference-location: margin
    references: references.bib
    code-fold: true
    code-overflow: wrap
    code-summary: "Näytä"
    code-tools: true

bibliography: references.bib
  
citation: true

editor: visual

execute:
  freeze: auto
  eval: false
  message: false
  warning: false

