project:
  type: book
  output-dir: docs

book:
  title: "Nollatoleranssi-hankkeen liitesivusto"
  author: "Oliver Saal"
  
  chapters:
    - index.qmd
    - part: "Kirjallisuuskatsaus"
      chapters:
        - kriteeristo.qmd
        - seulontamenetelma.qmd
        - prismakaavio.qmd
        - yleiskuvailu.qmd
    - part: "Katsauksen osahaut"
      chapters:
        - haku1.qmd
        - haku2.qmd
        - haku3.qmd
        - haku4.qmd
        - haku5.qmd
        - haku6.qmd
    - part: "Kyselyn valmistelu"
      chapters:
        - kyselynvalmistelu.qmd
    - part: "Datavalmistelu"
      chapters:
        - eksportointi.qmd
        - nimeaminen.qmd
        - valmistelu.qmd
    - part: "Mittariston validointi"
      chapters:
        - efabias.qmd
    - lahteet.qmd
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Etusivu"
        file: index.qmd
      - sidebar:kirjallisuuskatsaus
      - sidebar:katsauksenhaut
      - sidebar:kyselynvalmistelu
      - sidebar:datavalmistelu
      - sidebar:validointi
      - text: "Lähteet"
        file: lahteet.qmd
  
  sidebar:
    - id: kirjallisuuskatsaus
      title: "Kirjallisuuskatsaus"
      style: docked
      background: primary
      collapse-level: 2
      contents:
        - kriteeristo.qmd
        - seulontamenetelma.qmd
        - prismakaavio.qmd
        - yleiskuvailu.qmd
    
    - id: katsauksenhaut
      title: "Katsauksen osahaut"
      contents:
        - haku1.qmd
        - haku2.qmd
        - haku3.qmd
        - haku4.qmd
        - haku5.qmd
        - haku6.qmd
    
    - id: kyselynvalmistelu
      title: "Kyselyn valmistelu"
      contents:
        - kyselynvalmistelu.qmd
    
    - id: datavalmistelu
      title: "Datavalmistelu"
      contents:
        - eksportointi.qmd
        - nimeaminen.qmd
        - valmistelu.qmd
    
    - id: validointi
      title: "Mittariston validointi"
      contents:
        - efabias.qmd
format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    lang: fi
    crossref:
      chapters: true
    reference-location: margin
    references: references.bib
    
    code-fold: true
    code-overflow: wrap
    code-summary: "Näytä"

bibliography: references.bib
  
citation: true

editor: visual

execute:
  freeze: auto
  eval: false
  message: false
  warning: false

