project:
  type: book

book:
  title: "Nollatoleranssi-hankkeen liitesivusto"
  author: "Oliver Saal"
  
  chapters:
    - index.qmd
    - part: "Kirjallisuuskatsaus"
      chapters:
        - kriteeristo.qmd
        - haku1.qmd
        - haku2.qmd
        - haku6.qmd
    - part: "Kyselyn valmistelu"
      chapters:
        - kyselynvalmistelu.qmd
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Etusivu"
        file: index.qmd
      - sidebar:kirjallisuuskatsaus
      - sidebar:kyselynvalmistelu
  
  sidebar:
    - id: kirjallisuuskatsaus
      title: "Kirjallisuuskatsaus"
      style: docked
      background: primary
      collapse-level: 2
      contents:
        - kriteeristo.qmd
        - haku1.qmd
        - haku2.qmd
        - haku6.qmd
    
    - id: kyselynvalmistelu
      title: "Kyselyn valmistelu"
      contents:
        - kyselynvalmistelu.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    lang: fi
    crossref:
      chapters: true
    reference-location: margin
    citation-location: margin
    
    code-fold: true
    code-overflow: wrap
    code-summary: "Näytä"

editor: visual

execute:
  freeze: true
  eval: false

