# Kriteeristö {#sec-kriteeristo}

Kirjallisuuskatsauksessa sovellettiin kahta sisäänottokriteeristöä: kaikille osahauille yleiset kriteerit sekä hakukohtaiset kriteerit.

Yleiset kriteerit ovat listattuna taulukossa [-@tbl-kriteeristo-yleinen].

+------------------+----------------------------------------------------------------------------+-------------------------------------------------+
| Rajaus           | Sisäänottokriteeri                                                         | Rajauskriteeri                                  |
+==================+============================================================================+=================================================+
| **Julkaisuaika** | 1.1.2010 - 30.9.2023                                                       | Julkaistu ennen 1.1.2010                        |
|                  |                                                                            |                                                 |
|                  |                                                                            | Julkaistu 30.9.2023 jälkeen                     |
+------------------+----------------------------------------------------------------------------+-------------------------------------------------+
| **Metodologia**  | Empiirinen tutkimus laajasti ymmärrettynä:                                 | Ei-empiirinen tutkimus tai metatutkimus, kuten: |
|                  |                                                                            |                                                 |
|                  | -   Kvalitatiiviset tutkimusasetelmat (mm. haastattelut, havainnot)        | -   Teoreettiset analyysit                      |
|                  |                                                                            |                                                 |
|                  | -   Kvantitatiiviset tutkimusasetelmat (mm. rekisterit, kyselytutkimukset) | -   Käsiteanalyysit                             |
|                  |                                                                            |                                                 |
|                  | -   Toimintatutkimukset                                                    | -   Keskustelunavaukset                         |
|                  |                                                                            |                                                 |
|                  |                                                                            | -   Historialliset selvitykset                  |
|                  |                                                                            |                                                 |
|                  |                                                                            | -   Kirjallisuuskatsaukset                      |
|                  |                                                                            |                                                 |
|                  |                                                                            | -   Meta-analyysit                              |
+------------------+----------------------------------------------------------------------------+-------------------------------------------------+

: Hakuprosessille yhteiset hakurajaukset {#tbl-kriteeristo-yleinen}

Hakukohtaiset kriteerit ovat listattuna taulukossa [-@tbl-kriteeristo-hakukohtaiset].

+----------------+---------------------------------------+----------------------------------+---------------------------------------+----------------------------------+---------------------------------------+---------------------------------------+
| Rajaus         | Haku 1                                | Haku 2                           | Haku 3                                | Haku 4                           | Haku 5                                | Haku 6                                |
+================+=======================================+==================================+=======================================+==================================+=======================================+=======================================+
| Kohderyhmä     | Pelastustoimi                         | Pelastustoimi                    | Ensihoito                             | Ensihoito                        | Muut turvallisuustoimijat             | Pelastustoimi ja ensihoito            |
+----------------+---------------------------------------+----------------------------------+---------------------------------------+----------------------------------+---------------------------------------+---------------------------------------+
| Maantiede      | Suomi ja Ahvenanmaa                   | Suomi ja Ahvenanmaa              | Suomi ja Ahvenanmaa                   | Suomi ja Ahvenanmaa              | Suomi ja Ahvenanmaa                   | Eurooppa                              |
+----------------+---------------------------------------+----------------------------------+---------------------------------------+----------------------------------+---------------------------------------+---------------------------------------+
| Tutkimuskieli  | Suomi, ruotsi, englanti               | Suomi, ruotsi, englanti          | Suomi, ruotsi, englanti               | Suomi, ruotsi, englanti          | Suomi, ruotsi, englanti               | Englanti                              |
+----------------+---------------------------------------+----------------------------------+---------------------------------------+----------------------------------+---------------------------------------+---------------------------------------+
| Aineistotyyppi | -   Vertaisarvioidut tutkimusraportit | -   Opinnäytteet                 | -   Vertaisarvioidut tutkimusraportit | -   Opinnäytteet                 | -   Vertaisarvioidut tutkimusraportit | -   Vertaisarvioidut tutkimusraportit |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   Viranomaisraportit                |                                  | -   Viranomaisraportit                |                                  | -   Viranomaisraportit                |                                       |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   Yhdistysten tutkimusraportit      |                                  | -   Yhdistysten tutkimusraportit      |                                  |                                       |                                       |
+----------------+---------------------------------------+----------------------------------+---------------------------------------+----------------------------------+---------------------------------------+---------------------------------------+
| Tietolähteet   | -   SPEK:in julkaisut                 | -   Theseus                      | -   SPEK:in julkaisut                 | -   Theseus                      | -   Polamk:in julkaisut               | -   Scopus                            |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   Pelastusopiston julkaisut         | -   Yliopistojen julkaisukanavat | -   Pelastusopiston julkaisut         | -   Yliopistojen julkaisukanavat | -   Valto                             | -   Web of Science                    |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   Valto                             |                                  | -   Valto                             |                                  | -   Julkari                           | -   ProQuest                          |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   Julkari                           |                                  | -   Julkari                           |                                  | -   Scopus                            | -   BASE                              |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   Scopus                            |                                  | -   Scopus                            |                                  | -   Web of Science                    | -   OpenAlex                          |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   Web of Science                    |                                  | -   Web of Science                    |                                  | -   ProQuest                          |                                       |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   ProQuest                          |                                  | -   ProQuest                          |                                  | -   BASE                              |                                       |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   BASE                              |                                  | -   BASE                              |                                  | -   OpenAlex                          |                                       |
|                |                                       |                                  |                                       |                                  |                                       |                                       |
|                | -   OpenAlex                          |                                  | -   OpenAlex                          |                                  |                                       |                                       |
+----------------+---------------------------------------+----------------------------------+---------------------------------------+----------------------------------+---------------------------------------+---------------------------------------+

: Hakukohtaiset hakurajaukset {#tbl-kriteeristo-hakukohtaiset}

Tämän osion alaluvuissa käsitellään jokaista kriteeristöä tarkemmin.

## Julkaisuaika {#sec-kriteeristo-julkaisuaika}

Tiedonhaussa käytettiin seuraavaa julkaisuaikahaarukkaa: **1.1.2010 - 30.9.2023**.

Tämä koski tutkimusjulkaisun päiväystä, jolloin itse tutkimuksen toteutus voi olla tapahtunut myös ennen vuotta 2010.

Jos hakukone salli päivämääräkohtaisen rajauksen, käytettiin tarkkaa julkaisuaikahaarukkaa.

Jos hakukone salli vain vuositasoisen rajauksen, käytettiin vuosia 2010-2023, myös joskus vuosia 2010-2024. Tuolloin seulonnassa poistettiin tutkimukset, jotka ovat julkaistu aikavälillä 1.10.-31.12.2023 tai 1.1.2024 eteenpäin, sääntöjen samankaltaisuuden vuoksi.

## Metodologia {#sec-kriteeristo-metodologia}

Kirjallisuuskatsaus rajattiin vain empiirisiin tutkimuksiin.

Emme täten tarkistaneet esimerkiksi:

-   Teoreettisia analyyseja

-   Käsiteanalyyseja

-   Keskustelunavaukset

-   Historiallisia selvityksiä

-   Kirjallisuuskatsauksia

-   Meta-analyyseja

Empiiriseksi tutkimukseksi miellettiin sekä laadulliset että määrälliset asetelmat. Myös toimintatutkimukselliset asetelmat määriteltiin empiiriseksi, jos niihin sisältyi jonkin tapainen empiirinen tiedonkeruu. Laadunarvioinnin osalta arvioimme vain empiirisen osuuden jokaisesta tutkimuksesta.

## Kohderyhmä {#sec-kriteeristo-kohderyhma}

Kirjallisuuskatsauksen kohderyhmät jaettiin kolmeen kategoriaan:

-   Pelastustoimi

-   Ensihoito

-   Muut turvallisuustoimijat

### Pelastustoimi {#sec-kriteeristo-kohderyhma-pelastustoimi}

Pelastustoimella tarkoitetaan kaikkia pelastusalalla toimivia henkilöitä. Tämä koskettaa mm. operatiivista henkilökuntaa (esim. pelastajia ja hätäkeskusoperaattoreita), hallintohenkilökuntaa (esihenkilöitä, viestintää, talouspuolta), sopimuspalokunnissa toimivia henkilöitä, yhdistystoimijoita, pelastusalan opettajia ja opiskelijoita.

Kriteeri rajasi ulos ensihoidon operatiivinen henkilökunta käytännön syistä. Ensihoidon suomalaisen kontekstin haut toteutettiin erikseen, koska hakutyö katsottiin suunnitteluvaiheessa voivan olevan jopa laajempi kuin pelastusalan toimijoiden tiedonhaut.

Kriteeri rajasi myös ulos kaikki muut turvallisuustoimijat. Muita turvallisuustoimijoita tarkasteltiin erillisellä haulla. Heidän haunsa on kirjallisuuskatsauksen näkökulmasta vain vertaileva, koska katsaus ei kokonaisuudessaan käsitellyt yhtä laajasti muita turvallisuustoimijoita.

Rajaus toteutettiin käyttämällä hakulausekesanoja:

-   Suomeksi: `pelast* OR palo* OR sammut* OR hätäkesku*`

-   Ruotsiksi: `räddning* OR brand* OR släckning* OR nödcentral*`

-   Englanniksi: `"fire rescue*" OR "fire*fighter*" OR "rescue service*" OR "emergency respon*" OR "emergency personnel" AND NOT "medic"`

### Ensihoito {#sec-kriteeristo-kohderyhma-ensihoito}

Ensihoidolla tarkoitetaan ensihoidon operatiivista henkilökuntaa (mm. ambulanssikuljettajia ja ensihoitajia). Nämä ovat rajattuna omaksi kohderyhmäksi koska oletimme katsauksen suunnitteluvaiheessa, että kohderyhmää on tutkittu verrannollisesti enemmän kuin pelastustoimen kohderyhmää.

Kansainvälisen kontekstissa kohderyhmärajaus muodostui haasteelliseksi. Useissa maissa ensihoidon ja akuuttihoidon rajanveto ei ole hyvin selkeä, eikä englannin kielellä ensihoitajia tai ambulanssikuljettajia aina eroteta muusta akuuttihoidon henkilökunnasta (esim. "emergency medic" voi tarkoittaa sairaanhoitajaa sairaalan päivystyksessä). Ensisijaisesti seuloimme tuloksista pois selkeästi lääkäreitä ja sairaalassa tapahtuvien akuuttilääketieteellisten toimenpiteiden toteuttajia koskevat tutkimukset. Rajaus on kuitenkin voinut heikentää kirjallisuuskatsauksen saantia ja tarkkuutta.

Rajaus toteutettiin käyttämällä hakulausekesanoja:

-   Suomeksi: `ensihoit* OR sairaankuljet* OR ambulanssi*`

-   Ruotsiksi: `"första hjälp*" OR nödhjälp* OR ambulans* OR sjuktransport* OR förstavårdar*`

-   Englanniksi: `"medic" OR "emergency medic*" OR ambulance`

### Muut turvallisuustoimijat {#sec-kriteeristo-kohderyhma-muut}

Muut turvallisuustoimijat määriteltiin kirjallisuuskatsauksessa seuraaviksi: poliisi, rajavartiosto, puolustusvoimat ja yksityiset järjestyksenvalvojat. Koska muiden turvallisuustoimijoiden tiedonhaku tehtiin vertailevassa mielessä, emme keskittyneet yhtä paljon kohderyhmän saannin ja tarkkuuden kannalta tarkkaan rajaukseen kuin pelastustoimeen ja ensihoitoon kohdistuvissa hauissa.

Rajaus toteutettiin käyttämällä hakulausekesanoja:

-   Suomeksi: `poliisi* OR varti* OR puolustusvoim* OR sotila*`

-   Ruotsiksi: `polis* OR ordningsv?kt* OR försvars* OR soldat* OR gränsbevak* OR gränskontroll*`

-   Englanniksi: `police OR guard* OR defen?e contractor* OR steward OR soldier OR military personnel`

## Maantiede {#sec-kriteeristo-maantiede}

Maantieteellisesti haut rajattiin kahteen eri ryhmään:

-   Suomalaiset tutkimukset

-   Eurooppalaiset, ei-suomalaiset tutkimukset

Rajaus kohdistui tutkimuskontekstiin, eli missä maantieteellisessä ympäristössä empiirinen selvitys oli tehty.

### Suomalaiset tutkimukset {#sec-kriteeristo-maantiede-suomi}

Rajaus kohdistui Suomeen ja Ahvenanmaahan.

Rajaukset toteutettiin kahdella tavalla:

-   Suomeen ja Ahvenanmaahan kohdistuvat haut toteutettiin mm. suomeksi ja ruotsiksi (ks. @sec-kriteeristo-tutkimuskieli). Tällöin voitiin olettaa, että suomeksi toteutettu tutkimus oli myös toteutettu Suomessa. Ruotsinkielisen tutkimuksen kohdalla tarkistimme erikseen seulonnan yhteydessä, että tutkimus kohdistui Suomeen eikä Ruotsiin tai muihin maihin.

-   Englanninkielisten hakujen kohdalla hakulausekkeeseen tai hakukonerajauksiin lisättiin maantieteellinen rajaus, riippuen hakukoneen tai tietokannan ominaisuuksista.

### Eurooppalaiset tutkimukset {#sec-kriteeristo-maantiede-eurooppa}

Rajaus kohdistui Euroopan maihin, pois lukien Suomi ja Ahvenanmaa. Nämä maat olivat:

-   Alankomaat/Hollanti
-   Albania
-   Andorra
-   Armenia
-   Azerbaidzhan
-   Belgia
-   Bosnia ja Hertsegovina
-   Bulgaria
-   Englanti
-   Espanja
-   Färsaaret
-   Georgia
-   Irlanti
-   Islanti
-   Iso-Britannia (maat listattuna myös erikseen)
-   Italia
-   Itävalta
-   Kazakstan
-   Kosovo
-   Kreikka
-   Kroatia
-   Kypros
-   Latvia
-   Liechtenstein
-   Liettua
-   Luxemburg
-   Malta
-   Moldova
-   Monaco
-   Montenegro
-   Norja
-   Pohjois-Irlanti
-   Pohjois-Makedonia
-   Portugali
-   Puola
-   Ranska
-   Romania
-   Ruotsi
-   Saksa
-   San Marino
-   Serbia
-   Skotlanti
-   Slovakia
-   Slovenia
-   Sveitsi
-   Tanska
-   Tšekki
-   Turkki
-   Ukraina
-   Unkari
-   Valko-Venäjä
-   Vatikaani
-   Venäjä
-   Viro
-   Wales

Rajaukset toteutettiin joko hakulausekkeessa tai hakukonerajauksissa, riippuen tietokannan tai hakukoneen ominaisuuksista. Seulonnan yhteydessä tarkistettiin myös tutkimusten toteutusmaat ennen sisäänottopäätöstä.

## Tutkimuskieli {#sec-kriteeristo-tutkimuskieli}

Tutkimusraportteja haettiin kolmella kielellä: **suomi, ruotsi** ja **englanti**.

Hauissa 1-5 käytettiin kaikkia kolmea kieltä, jolloin määrittelimme jokaiselle kielelle oman hakulausekkeen. Haussa 6 käytettiin vain englannin kieltä.

Seulonnassa karsittiin pois kaikki tutkimukset, jotka olivat julkaistuja muilla kielillä ja joille ei löytynyt tutkimuskielirajausta vastaavaa kokotekstiversiota.

## Aineistotyyppi {#sec-kriteeristo-aineistotyyppi}

Kirjallisuuskatsauksessa haettiin neljää aineistotyyppiä:

-   Vertaisarvioidut tutkimusartikkelit

-   Viranomaisraportit

-   Yhdistysten tutkimusraportit

-   Opinnäytetyöt

### Vertaisarvioidut tutkimusraportit {#sec-kriteeristo-aineistotyyppi-vertaisarvioidut}

Tutkimus laskettiin vertaisarvioiduksi tutkimusraportiksi, jos jokin tai kaikki seuraavista kriteereistä täyttyi:

-   Tutkimus oli julkaistu tieteellisestä aikakauslehdestä, jonka kuvaus selkeästi osoitti vertaisarviointiprosessin käytön

-   Tutkimuksella oli vertaisarviointitunnus tai muu maininta vertaisarvioinnista kokotekstissä

-   Tutkimus oli julkaistu julkaisijalla, jonka tiedetään harjoittavan vertaisarviointia (koski lähinnä kirjateoksia)

Opinnäytetyöt ja konferenssijulkaisut eivät laskettu vertaisarvioiduiksi tässä kirjallisuuskatsauksessa. Opinnäytetöiden osalta seurasimme toista menettelyä (ks. alla). Konferenssijulkaisujen mukaanotto olisi voinut tuottaa suuria määriä kaksoiskappaleita. Tämän lisäksi konferenssiesitelmistä voidaan yleensä odottaa vertaisarvioitua tutkimusjulkaisua, jolloin kyseinen tutkimus läpäisisi seulan joka tapauksessa. On kuitenkin mahdollisuus, että rajaus tuotti pienen määrän virheellisiä negatiiveja, jos jokin esitelmä olisi ollut julkaisut vastikään, eikä tutkimus vielä olisi ehtinyt julkaistavaksi aikakauslehdessä tai kirjassa.

Rajaus toteutettiin hakukoneesta riippuen hakuvalinnoilla tai seulonnassa.

### Viranomaisraportit {#sec-kriteeristo-aineistotyyppi-viranomaisraportit}

Viranomaisraportilla tarkoitetaan Suomen viranomaisten julkaisemia tutkimusraportteja ja katsauksia. "Viranomainen" on tässä kontekstissa määritelty valtionhallintoon, ministeriöihin ja niiden hallinnonalalla toimiviin virastoihin. Täten tarkistimme seuraavat viranomaiset:

-   Poliisiammattikorkeakoulu ja Pelastusopisto

-   Sisäministeriö ja Puolustusministeriö

-   Työterveyslaitos, Terveyden ja hyvinvoinnin laitos

Rajaus toteutettiin hakemalla raportteja niitä julkaisevista palveluista. Joissain hakukoneissa rajausta toteutettiin myös tulosmuotojen hakuvalinnoissa. Jokaisen haun tietokantakohtaiset rajaukset ovat esitelty osahaun omalla sivulla tällä liitesivustolla.

### Yhdistysten tutkimusraportit {#sec-kriteeristo-aineistotyyppi-yhdistysraportit}

Yhdistysten tutkimusraporteilla tarkoitetaan Suomen pelastusalan järjestöjen itse julkaisemia tutkimusraportteja ja katsauksia. Julkaisevia järjestöjä on yksi: Suomen Pelastusalan Keskusjärjestö, SPEK. Haimme SPEK:n tuottamia tutkimusjulkaisuja suoraan heidän verkkosivuiltaan, [Tutkimukset - SPEK](https://www.spek.fi/vaikuttaminen/tutkimukset/) (haettu 30.1.2024).

### Opinnäytetyöt {#sec-kriteeristo-aineistotyyppi-opinnaytteet}

Opinnäytteillä tarkoitetaan Suomen korkeakouluissa tuotettuja opintojen opinnäytetöitä, jotka liittyvät kolmannen syklin tai tutkimuksellisen opetuksen tutkintoihin. Näitä ovat kandidaatti-, maisteri-, lisensiaatti-, tohtori-, AMK- ja ylempään AMK-tutkintoihin liittyvät opinnäytteet.

Ulkopuolelle rajattiin mahdolliset seminaarityöt, jotka eivät liity suoraan korkeakoulujen tutkintoihin (esim. toisen asteen tutkintojen työt).

Myös toisen koulutussyklin opinnäytetyöt (esimerkiksi lähihoitajien töitä) rajattiin pois. Rajaus tehtiin ensisijaisesti käytännön syistä, koska meidän tietääksemme näitä töitä ei yleensä julkaista avoimesti eikä Suomessa ole tietokantoja niiden hakemiselle.

Rajaus toteutettiin hakemalla opinnäytetöitä korkeakoulujen julkaisupalveluista. Seulonnassa poistettiin mahdollisia tuloksia, jotka eivät olleet opinnäytteitä (esim. rinnakkaistallennettuja tutkimusartikkeleita).

## Tietolähteet {#sec-kriteeristo-tietolahteet}

Käytimme kirjallisuuskatsauksessa seuraavia tietolähteitä:

-   Yhdistysten ja yhteisöjen julkaisukanavat
    -   Suomen Pelastusalan Keskusjärjestö SPEK:n julkaisut
    -   Pelastusopiston julkaisut
    -   Valto - Valtioneuvoston yhteinen julkaisuarkisto
    -   Julkari - Sosiaali- ja terveysministeriön hallinnonalan avoin julkaisuarkisto
-   Korkeakoulujen opinnäytteiden julkaisukanavat
    -   Theseus-palvelu (ammattikorkeakoulujen tietokannat, Poliisiammattikorkeakoulun julkaisut)
    -   Yliopistojen julkaisukanavat (ks. alla)
    -   Pelastusopiston verkkokirjasto
-   Tieteelliset hakukoneet
    -   Scopus
    -   Web of Science (Web of Science Core Collection, MEDLINE)
    -   ProQuest (Ebook Central, Social Science Premium Collection)
    -   Bielefeld Academic Search Engine BASE
    -   OpenAlex

### Yhdistysten ja yhteisöjen julkaisukanavat {#sec-kriteeristo-tietolahteet-yhdistykset}

Tarkistimme **Suomen Pelastusalan Keskusjärjestön julkaisut** [heidän omilta sivuiltaan](https://www.spek.fi/vaikuttaminen/tutkimukset/) (haettu 30.1.2024). Koska näitä ei voitu hakea hakukoneesta, tulokset sisällytettiin muina tuloksina.

Samoin **Pelastusopiston julkaisut** tarkistettiin käsin [heidän omilta sivuiltaan](https://www.pelastusopisto.fi/kirjasto-ja-tietopalvelut/julkaisut-ja-aineistot/) (haettu 30.1.2024) ja sisällytettiin muina tuloksina.

Ministeriöiden ja valtionhallinnon julkaisut haettiin kootusti **Valto**-[hakupalvelusta](https://julkaisut.valtioneuvosto.fi/) (haettu 30.1.2024).

Muiden valtiollisten tutkimusorganisaatioiden julkaisut haettiin **Julkari**-[hakupalvelusta](https://www.julkari.fi/) (haettu 30.1.2024).

### Korkeakoulujen opinnäytteiden julkaisukanavat {#sec-kriteeristo-tietolahteet-opinnaytteet}

Kaikki Suomen ammattikorkeakoulujen opinnäytteet julkaistaan yhteisesti **Theseus**-[hakupalvelussa](https://www.theseus.fi/) (haettu 30.1.2024). Haimme ammattikorkeakoulujen osalta kootusti opinnäytteet täältä. On kuitenkin huomattava, että palvelun käyttöönottoa edeltäviä opinnäytetöitä on viety vaihtelevasti palveluun, riippuen ammattikorkeakoulusta. Tietoa on myös huonosti saatavilla vanhemmista opinnäytteistä.

Huomasimme kirjallisuuskatsauksen aikana, ettei **Pelastusopiston ammattikorkeakoulutasoisia opinnäytetöitä** olla viety vuotta 2013 aiemmin Theseukseen. Suoritimme siksi erikseen haut [Pelastusopiston verkkokirjaston](https://peo.verkkokirjasto.fi/) hakukoneen kautta (haettu 30.1.2024).

**Suomen yliopistot** käyttävät pääsääntöisesti omia opinnäytejulkaisukanavia. Nämä ovat listattuna taulukossa [-@tbl-kriteeristo-yliopistojenjulkaisukanavat] alla verkko-osoitteineen:

+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Yliopisto                       | Kanavan nimi            | Osoite                                                                       | Huomioita                                                                                                                               |
+=================================+=========================+==============================================================================+=========================================================================================================================================+
| Aalto-yliopisto                 | Aaltodoc                | <https://aaltodoc.aalto.fi/?locale-attribute=fi>                             |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Helsingin yliopisto             | E-thesis                | <https://ethesis.helsinki.fi/>                                               | Saatavuus vaihtelee tiedekunnan mukaan, mutta yleisesti ottaen 2010-luvun puolen välin jälkeen julkastut tutkielmat ovat käytettävissä. |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Itä-Suomen yliopisto            | UEF eRepo               | <https://erepo.uef.fi/>                                                      |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Jyväskylän yliopisto            | JYX                     | <https://jyx.jyu.fi/>                                                        |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Lapin yliopisto                 | Lauda                   | <https://lauda.ulapland.fi/>                                                 | Maisteritutkielmat vuodesta 2014 eteenpäin.                                                                                             |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| LUT-yliopisto                   | LUTPub                  | <https://lutpub.lut.fi/>                                                     |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Oulun yliopisto                 | Jultika[^kriteeristo-1] | <http://jultika.oulu.fi/>                                                    | Kandidaattitutkielmat vuodesta 2016 eteenpäin, maisteritutkielmat vuodesta 2013 eteenpäin.                                              |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Svenska handelshögskolan Hanken | DHanken                 | <https://helda.helsinki.fi/communities/61c8694f-3453-4bd3-a197-32fee3108f66> |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Taideyliopisto                  | Taju                    | <https://taju.uniarts.fi/>                                                   |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Tampereen yliopisto             | Trepo                   | <https://trepo.tuni.fi/>                                                     |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Turun yliopisto                 | UTUPub                  | <https://www.utupub.fi/>                                                     |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Vaasan yliopisto                | Osuva                   | <https://osuva.uwasa.fi/>                                                    |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Åbo Akademi                     | Doria                   | <https://www.doria.fi/handle/10024/3981>                                     |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Maanpuolustuskorkeakoulu        | Doria                   | <https://www.doria.fi/handle/10024/72633>                                    |                                                                                                                                         |
+---------------------------------+-------------------------+------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+

: Yliopistojen julkaisukanavat {#tbl-kriteeristo-yliopistojenjulkaisukanavat}

[^kriteeristo-1]: Jultika vaihtui kesken kirjallisuuskatsauksen teon OuluREPO-palveluksi. Toteutimme kaikki haut Jultika-palvelussa, koska palvelun verkkosivujen mukaan tiedot vuodelta 2023 olivat ajantasaisia molemmissa palveluissa.

### Tieteelliset hakukoneet ja tietokannat {#sec-kriteeristo-tietolahteet-tietokannat}

Haimme seuraavista hakupalveluista kirjallisuutta (käytetyt tietokannat suluissa):

-   Scopus

-   Web of Science (Web of Science Core Collection, MEDLINE)[^kriteeristo-2]

-   ProQuest (Ebook Central, Social Science Premium Collection)

-   Bielefeld Academic Search Engine BASE

-   OpenAlex

[^kriteeristo-2]: Haku 5:ssä haettiin inhimillisen virheen takia kaikista Web of Science-palvelun hakukoneista. Ks. @sec-haku5.

Nämä tietolähteet valittiin osittain systemaattisten kirjallisuuskatsausten suosituksen myötä [ks. @gusenbauer2020].
