# Nimeäminen {#sec-nimeaminen}

Seuraavaksi muuttujat nimettiin hankkeessa vakiintuneiden lyhenteiden mukaisesti. Tässä listataan nimeämiset lomakkeen (ja täten datatiedoston) järjestyksessä.

Alkuperäiset nimeämiset löytyvät `csv`-tiedostosta tämän verkkosivun lähdekoodissa, kansiossa `data > muuttujiennimet.csv`.

Alkuperäiset data-arvot löytyvät niinikään `csv`-tiedostosta sijainnissa `data > alkuperaisetarvot.csv`.

## Metatiedot {#sec-nimeaminen-metatiedot}

1.  **Linkkiversio** jätettiin sellaiseksi.
2.  **Kieliversio** jätettiin sellaiseksi.
3.  **k1**: Olen tietoinen minusta kerättävistä tiedoista sekä niiden käsittelystä, ja annan suostumukseni tietojen keruuseen:
4.  **k2**: Mihin organisaatioon/toimialaan kuulut?

## Organisaation sisäiset kokemukset {#sec-nimeaminen-sisaisetkokemukset}

5.  **k3\_\[1-7\]**: Kuinka usein olet itse kohdannut seuraavia epäasiallisen kohtelun muotoja organisaatiosi sisällä viimeisen 12 kuukauden aikana? (7 alakysymystä)
6.  **k4\_\[1-7\]**: Kuinka usein olet havainnut kollegan kohdanneen seuraavia epäasiallisen kohtelun muotoja organisaatiosi sisällä viimeisen 12 kuukauden aikana? (7 alakysymystä)
7.  **k5\_\[1-9\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation sisäisestä verbaalisesta väkivallasta:
    1.  Ensimmäinen luku: 9 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
8.  **k6\_\[1-10\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation sisäisestä omaisuuden vahingoittamisesta tai varastamisesta:
    1.  Ensimmäinen luku: 10 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
9.  **k7\_\[1-14\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation sisäisestä uhkailusta:
    1.  Ensimmäinen luku: 14 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
10. **k8\_\[1-11\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation sisäisestä fyysisestä väkivallasta:
    1.  Ensimmäinen luku: 11 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
11. **k9\_\[1-10\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation sisäisestä seksuaalisesta häirinnästä tai väkivallasta:
    1.  Ensimmäinen luku: 10 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
12. **k10\_\[1-11\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation sisäisestä vihamielisyydestä tai epäasiallisesta kohtelusta:
    1.  Ensimmäinen luku: 11 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
13. **k11\_\[1-16\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation sisäisestä syrjinnästä:
    1.  Ensimmäinen luku: 16 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki

## Organisaation ulkopuoliset kokemukset {#sec-nimeaminen-ulkopuolisetkokemukset}

14. **k12\_\[1-7\]**: Kuinka usein olet itse kohdannut seuraavia epäasiallisen kohtelun muotoja organisaatiosi ulkopuoliselta henkilöltä viimeisen 12 kuukauden aikana? (7 alakysymystä)
15. **k13\_\[1-7\]**: Kuinka usein olet havainnut kollegan kohdanneen seuraavia epäasiallisen kohtelun muotoja organisaatiosi ulkopuoliselta henkilöltä viimeisen 12 kuukauden aikana? (7 alakysymystä)
16. **k14\_\[1-9\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation ulkopuolelta tulleesta verbaalisesta väkivallasta:
    1.  Ensimmäinen luku: 9 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
17. **k15\_\[1-10\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation ulkopuolelta tulleesta omaisuuden vahingoittamisesta tai varastamisesta:
    1.  Ensimmäinen luku: 10 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
18. **k16\_\[1-14\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation ulkopuolelta tulleesta uhkailusta:
    1.  Ensimmäinen luku: 14 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
19. **k17\_\[1-11\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation ulkopuolelta tulleesta fyysisestä väkivallasta:
    1.  Ensimmäinen luku: 11 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
20. **k18\_\[1-10\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation ulkopuolelta tulleesta seksuaalisesta häirinnästä tai väkivallasta:
    5.  Ensimmäinen luku: 10 alakysymystä
    6.  Toinen luku: (1) Minä koin, (2) Kollegani koki
21. **k19\_\[1-11\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation ulkopuolelta tulleesta vihamielisyydestä tai epäasiallisesta kohtelusta:
    1.  Ensimmäinen luku: 11 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki
22. **k20\_\[1-7\]\_\[1-2\]**: Voitko tarkentaa kokemuksiasi tai havaintojasi organisaation ulkopuolelta tulleesta syrjinnästä:
    1.  Ensimmäinen luku: 7 alakysymystä
    2.  Toinen luku: (1) Minä koin, (2) Kollegani koki

## Kohtelun vaikutukset {#sec-nimeaminen-vaikutukset}

23. **k21\_\[1-3\]**: Miten vakavia sinuun kohdistuneen epäasiallisen käytöksen vaikutukset olivat?
    1.  Fyysiset vaikutukset
    2.  Psyykkiset vaikutukset
    3.  Ammatilliset vaikutukset
24. **k22\_\[1-3\]**: Miten pitkäkestoisia sinuun kohdistuneen epäasiallisen kohtelun vaikutukset olivat?
    1.  Fyysiset vaikutukset
    2.  Psyykkiset vaikutukset
    3.  Ammatilliset vaikutukset
25. **k22\_\[1-3\]\_1**: ... Jatkuu tällä hetkellä
26. **k23\_\[1-11\]**: Miten reagoit epäasiallisen kohtelun kokemukseesi? (11 alakysymystä)

## Ilmoitusjärjestelmät ja työolot {#sec-nimeaminen-ilmoitusjarjestelmat}

27. **k24\_\[1-3\]**: Onko organisaatiollasi käytössä ilmoitusjärjestelmä, jossa voit ilmoittaa epäasiallisen kohtelun tilanteista?
    1.  Organisaation sisällä tapahtuneille tilanteille
    2.  Organisaation ulkopuolelta tulleelle kohtelulle
    3.  Sekä sisäiset että ulkoiset tilanteet yhdessä järjestelmässä
28. **k25\_\[1-3\]**: Onko organisaatiollasi tarjolla koulutusta ilmoitusjärjestelmän käyttöön?
    1.  Organisaation sisällä tapahtuneille tilanteille
    2.  Organisaation ulkopuolelta tulleelle kohtelulle
    3.  Sekä sisäiset että ulkoiset tilanteet yhdessä järjestelmässä
29. **k26\_\[1-18\]**: Ota kantaa seuraaviin väitteisiin ilmoitusjärjestelmistä ja niiden käytöstä (18 alakysymystä)
30. **k27\_\[1-4\]**: Seuraavat väittämät koskevat työtilannettasi ja sitä koskevia tuntemuksiasi. Miten usein seuraavat väittämät kuvaavat tilannettasi?
    1.  Tunnen itseni henkisesti uupuneeksi työssäni
    2.  En ole kiinnostunut enkä innostunut työstäni
    3.  Minun on vaikea pysyä tarkkaavaisena työssäni
    4.  En pysty hallitsemaan tunteitani työssäni

## Toimenpiteet {#sec-nimeaminen-toimenpiteet}

31. **k28\_\[1-12\]**: Onko organisaatiossasi käytössä seuraavia epäasialliseen kohteluun liittyviä toimenpiteitä tai ohjeita? (12 alakysymystä)
32. **k29\_\[1-12\]**: Miten edellä olevat toimet mielestäsi vaikuttavat epäasiallisen kohtelun esiintyvyyteen? (12 alakysymystä)
33. **k30\_\[1-13\]**: Miten hyödyllisinä koet seuraavat ehdotetut toimenpiteet epäasiallisen kohtelun estämiseksi tai vähentämiseksi? (13 alakysymystä)

## Taustakysymykset {#sec-nimeaminen-taustakysymykset}

34. **k31**: Mikä sukupuolesi on?
35. **k32**: Millaisella työrytmityksellä olet töissä pelastuslaitoksella tai ensihoidossa?
36. **k33**: Kuinka monta tuntia käytät keskimäärin aikaa palokuntatoimintaan viikossa, poisluettuna varallaolo?
37. **k34**: Teetkö varallaoloa tai oletko sopimuksenvaraisessa hälytysvalmiudessa?
38. **k35**: Kuinka monta tuntia teet varallaoloa keskimäärin kuukaudessa?
39. **k36\_\[1-7\]**: Millaisia toimintoja teet sopimuspalokunnassasi tai palokuntayhdistyksessäsi? (7 alakysymystä)
40. **k37**: Millaisella rytmityksellä toimit organisaatiossasi?
41. **k38**: Missä asemassa toimit organisaatiossasi pääsääntöisesti? (Järjestöt ja koulutusorganisaatiot)
42. **k39**: Missä asemassa toimit organisaatiossasi pääsääntöisesti? (Pelastuslaitokset ja ensihoito sekä sopimuspalokunnat ja palokuntayhdistykset)
43. **k40**: Mihin ammattiryhmään kuulut?
44. **k41**: Kuinka kauan olet toiminut pelastusalalla tai ensihoidossa?
45. **k42\_\[1-3\]\_\[1-3\]**: Onko sinulla ollut viimeisen 12 kuukauden aikana aikeita tai suunnitelmia muuttaa tilannettasi seuraavilla tavoilla, tai oletko jo muuttanut tilannettasi?
    1.  Ensimmäinen luku: (1) Muuttaa tehtävänkuvaani, (2) Vaihtaa organisaatiotani, (3) Lähteä alalta
    2.  Toinen luku: (1) Olen harkinnut, (2) Olen toteuttamassa, (3) Olen jo tehnyt
46. **k43**: Voitko kertoa syitä muutoksellesi tai sen aikeille?
