<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fi" xml:lang="fi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Nollatoleranssi-hankkeen liitesivusto - 32&nbsp; Toimintaohjelmaan kohdistuvien asenteiden faktorianalyysi</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./muutosaie_sem.html" rel="next">
<link href="./tayvkayttoonotto_validointi.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Ei tuloksia",
    "search-matching-documents-text": "tulokset",
    "search-copy-link-title": "Kopioi linkki hakuun",
    "search-hide-matches-text": "Piilota loput tulokset",
    "search-more-match-text": "tulos tässä dokumentissa",
    "search-more-matches-text": "tulosta tässä dokumentissa",
    "search-clear-button-title": "Tyhjennä",
    "search-detached-cancel-button-title": "Peruuta",
    "search-submit-button-title": "Lähetä",
    "search-label": "Hae"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Nollatoleranssi-hankkeen liitesivusto</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Hae"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Vaihda navigointi" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Etusivu</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-kirjallisuuskatsaus" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Kirjallisuuskatsaus</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-kirjallisuuskatsaus">    
        <li>
    <a class="dropdown-item" href="./kriteeristo.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Kriteeristö</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./seulontamenetelma.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Seulontamenetelmä</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./hakuprosessi.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Hakuprosessi ja PRISMA-kaavio</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./yleiskuvailu.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Tulosten yleiskuvaus</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./katsausartikkeli.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Katsausartikkeli</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-katsauksen-osahaut" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Katsauksen osahaut</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-katsauksen-osahaut">    
        <li>
    <a class="dropdown-item" href="./haku1.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Haku 1</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./haku2.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Haku 2</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./haku3.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Haku 3</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./haku4.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Haku 4</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./haku5.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Haku 5</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./haku6.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Haku 6</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-kyselyprosessi" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Kyselyprosessi</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-kyselyprosessi">    
        <li>
    <a class="dropdown-item" href="./kyselynvalmistelu.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kyselyn valmistelu</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tiedonkeruu.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Tiedonkeruu</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./eksportointi.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Eksportointi</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nimeaminen.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Nimeäminen</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./valmistelu.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Valmistelu</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./puhdistaminen.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Puhdistaminen</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./anonymisointi.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Anonymisointi</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./koodikirja.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Koodikirjan rakentaminen</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./datatarkistus.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Datatarkistus</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-kyselyn-tulokset" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Kyselyn tulokset</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-kyselyn-tulokset">    
        <li>
    <a class="dropdown-item" href="./metatiedot.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Kyselyn metatiedot</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./taustamuuttujat.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Taustamuuttujat</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./esiintyvyys.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Epäasiallisen ja väkivaltaisen kohtelun esiintyvyys</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./vaikutukset.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Koetun kohtelun vaikutukset</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ilmoitusjarjestelmat.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Ilmoitusjärjestelmät</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./organisaatiotoimet.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Organisaatiotoimet</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ryhmavertailut.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Ryhmävertailut</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./korrelaatiosuhteet.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Korrelaatiosuhteet</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-monimuuttujamallit" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Monimuuttujamallit</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-monimuuttujamallit">    
        <li>
    <a class="dropdown-item" href="./kohtelu_validointi.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Epäasiallisen ja väkivaltaisen kohtelun esiintyvyyden mittarin validointi</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ilmoasenteet_validointi.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Ilmoitusjärjestelmäasenteiden verkostoanalyysi</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tayvkayttoonotto_validointi.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Toimintaohjelman käyttöönoton ryhmittelyanalyysi</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tayvasenteet_validointi.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Toimintaohjelmaan kohdistuvien asenteiden faktorianalyysi</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./muutosaie_sem.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Muutosaikeiden ennustaminen työuupumuksen ja kohtelun avulla</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-esitykset-ja-kirjoitukset" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Esitykset ja kirjoitukset</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-esitykset-ja-kirjoitukset">    
        <li>
    <a class="dropdown-item" href="./deibseminaari.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Pelastusalan DEIB-seminaari</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./blogi1.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Blogi: Epäasiallisuutta ja väkivaltaa esiintyy pelastusalalla ja ensihoidossa laajasti</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./blogi2.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Blogi: Työyhteisön epäasiallisuudet ja väkivalta heikentävät alan pitovoimaa</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./blogi3.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Blogi: Epäasiallisuuksia ja väkivaltaa ei raportoida, jos ilmoitusjärjestelmää ei ole olemassa</span></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./blogi4.html" rel="" target="">
 <span class="dropdown-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Tasa-arvon ja yhdenvertaisuuteen tähtäävät toimenpiteet purevat osittain</span></span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./lahteet.html" rel="" target="">
 <span class="menu-text">Lähteet</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Vaihda sivupalkki" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./tayvasenteet_validointi.html"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Toimintaohjelmaan kohdistuvien asenteiden faktorianalyysi</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Vaihda sivupalkki" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kohtelu_validointi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Epäasiallisen ja väkivaltaisen kohtelun esiintyvyyden mittarin validointi</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ilmoasenteet_validointi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Ilmoitusjärjestelmäasenteiden verkostoanalyysi</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tayvkayttoonotto_validointi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Toimintaohjelman käyttöönoton ryhmittelyanalyysi</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tayvasenteet_validointi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Toimintaohjelmaan kohdistuvien asenteiden faktorianalyysi</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./muutosaie_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Muutosaikeiden ennustaminen työuupumuksen ja kohtelun avulla</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sisällysluettelo</h2>
   
  <ul>
  <li><a href="#muuttujien-valitseminen-malliin" id="toc-muuttujien-valitseminen-malliin" class="nav-link active" data-scroll-target="#muuttujien-valitseminen-malliin"><span class="header-section-number">32.1</span> Muuttujien valitseminen malliin</a></li>
  <li><a href="#datasopivuuden-tarkastus" id="toc-datasopivuuden-tarkastus" class="nav-link" data-scroll-target="#datasopivuuden-tarkastus"><span class="header-section-number">32.2</span> Datasopivuuden tarkastus</a></li>
  <li><a href="#efa-mallien-asettaminen" id="toc-efa-mallien-asettaminen" class="nav-link" data-scroll-target="#efa-mallien-asettaminen"><span class="header-section-number">32.3</span> EFA-mallien asettaminen</a></li>
  <li><a href="#cfa-mallien-asettamista" id="toc-cfa-mallien-asettamista" class="nav-link" data-scroll-target="#cfa-mallien-asettamista"><span class="header-section-number">32.4</span> CFA-mallien asettamista</a></li>
  <li><a href="#yhteenveto" id="toc-yhteenveto" class="nav-link" data-scroll-target="#yhteenveto"><span class="header-section-number">32.5</span> Yhteenveto</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-tayvasenteet_validointi" class="quarto-section-identifier"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Toimintaohjelmaan kohdistuvien asenteiden faktorianalyysi</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Koodi</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Näytä kaikki koodi</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Piilota kaikki koodi</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Näytä lähdekoodi</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Tässä osiossa tarkistamme toimintaohjelmaan kohdistuvien asenteiden faktorirakenteen.</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HH) <span class="co"># VIF-arvon laskeminen</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EFAtools) <span class="co"># Datasopivuuden tarkastusfunktiot</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan) <span class="co"># EFA- ja CFA-mallien asettaminen</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semTools) <span class="co"># Mallien vertailufunktio</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"output/anonymisoitudata.csv"</span>, <span class="at">tryLogical =</span> <span class="cn">FALSE</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="muuttujien-valitseminen-malliin" class="level2" data-number="32.1">
<h2 data-number="32.1" class="anchored" data-anchor-id="muuttujien-valitseminen-malliin"><span class="header-section-number">32.1</span> Muuttujien valitseminen malliin</h2>
<p>Valitsimme kaikki 12 pelastustoimen tasa-arvon ja yhdenvertaisuuden toimintaohjelman tehokkuuden arvioinnin muuttujat mukaan analyysiin:</p>
<ul>
<li><code>k29_1</code>: Tasa-arvo- tai yhdenvertaisuussuunnitelma</li>
<li><code>k29_2</code>: Toimintaohjeet epäasialliseen käytökseen, häirintään tai seksuaaliseen häirintään reagointiin</li>
<li><code>k29_3</code>: Henkilöstön turvallisuusselvitykset</li>
<li><code>k29_4</code>: Ohjeet alaikäisten koskemattomuuden turvaamiselle</li>
<li><code>k29_5</code>: Nuorten kanssa toimivien rikostaustojen tarkastaminen</li>
<li><code>k29_6</code>: Ohjeet ahdistelutilanteen käsittelyyn</li>
<li><code>k29_7</code>: Ohjeet uhka- ja väkivaltatilanteen käsittelyyn</li>
<li><code>k29_8</code>: Ilmoitusjärjestelmä epäasiallisen kohtelun raportoimiseksi</li>
<li><code>k29_9</code>: Koulutus uhka- ja väkivaltatilanteiden kohtaamiseen</li>
<li><code>k29_10</code>: Koulutus epäasiallisen kohtelun tunnistamiseen</li>
<li><code>k29_11</code>: Keskustelutilaisuuksia tasa-arvo- ja yhdenvertaisuusaiheista</li>
<li><code>k29_12</code>: Henkilöstön infotilaisuudet organisaation yhdenvertaisuustilanteesta</li>
</ul>
</section>
<section id="datasopivuuden-tarkastus" class="level2" data-number="32.2">
<h2 data-number="32.2" class="anchored" data-anchor-id="datasopivuuden-tarkastus"><span class="header-section-number">32.2</span> Datasopivuuden tarkastus</h2>
<div class="cell">
<details>
<summary>EFA-mallin sopivuustestit</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mahalanobiksen etäisyys ja merkitsevyys</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>mahalanobis <span class="ot">&lt;-</span> <span class="fu">mahalanobis</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">center =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span> <span class="fu">colMeans</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">cov =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span> <span class="fu">cov</span>(<span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>mahalanobis.p <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mahalanobis) <span class="sc">|&gt;</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.double</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pchisq</span>(</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span> <span class="fu">ncol</span>() <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Kerätään kaikki tulokset yhteen listaan</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Mahalanobiksen pohjalta poistettavat vastaajat</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>poisto_n <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mahalanobis.p <span class="sc">&lt;</span> .<span class="dv">001</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Bartlettin testi</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>bart <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">BARTLETT</span>()</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co"># KMO-suure</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>kmosuure <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">KMO</span>()</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Korrelaatiomatriisin determinantti</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>determinantti <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">det</span>()</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="co"># VIF-arvot</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>vif <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vif</span>()</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Hullin menetelmä</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>hull <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">HULL</span>(</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"ML"</span>,</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">eigentype =</span> <span class="st">"SMC"</span>,</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">decision_rule =</span> <span class="st">"percentile"</span></span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Mahalanobiksen etäisyyden merkitsevyystestaus (p &lt; .001) osoittaa, että yhteensä 53 vastaajaa pitäisi poistaa mallista.</p>
<p>KMO-suureen koko on 0.9036303.</p>
<p>Bartlettin testi on merkitsevä (<span class="math inline">\(\chi^2 = 9262.1343736, \text{df} = 66, p = 0\)</span>).</p>
<p>Korrelaatiomatriisin determinantti on 1.1301967^{-4}.</p>
<p>Kaikki VIF-arvot ovat alle 10. Suurin VIF-arvo on <span class="math inline">\(\text{VIF} = 4.8\)</span> (<code>k29_11</code>).</p>
<p>Hullin menetelmän tulokset riippuvat käytetystä sopivuusindeksistä. CAF-indeksi ehdottaa 4 faktoria, CFI ehdottaa 1 faktoria ja RMSEA ehdottaa 1 faktoria.</p>
</section>
<section id="efa-mallien-asettaminen" class="level2" data-number="32.3">
<h2 data-number="32.3" class="anchored" data-anchor-id="efa-mallien-asettaminen"><span class="header-section-number">32.3</span> EFA-mallien asettaminen</h2>
<p>Kokeilimme kahta mallia: Yhden faktorin mallia (A) ja neljän faktorin mallia (B). Jätimme analyysista pois kaikki Mahalanobiksen etäisyyden rajan rikkoneet vastaajat.</p>
<div class="cell">
<details>
<summary>Mahalanobiksen etäisyyden rikkoneiden vastaajien poisjättäminen</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data.valitut <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mahalanobis.p <span class="sc">&gt;</span> .<span class="dv">001</span> <span class="sc">|</span> <span class="fu">is.na</span>(mahalanobis.p))</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Malli A</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Malli B</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<details>
<summary>EFA-malli A</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>efa.malli.A <span class="ot">&lt;-</span> data.valitut <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">efa</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">nfactors =</span> <span class="dv">1</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">rotation =</span> <span class="st">"oblimin"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimator =</span> <span class="st">"ML"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.A <span class="ot">&lt;-</span> <span class="fu">summary</span>(</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  efa.malli.A,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">TRUE</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ci =</span> <span class="cn">TRUE</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">efa =</span> <span class="cn">TRUE</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">cutoff =</span> <span class="dv">0</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.A</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>This is lavaan 0.6-18 -- running exploratory factor analysis

  Estimator                                         ML
  Rotation method                      OBLIMIN OBLIQUE
  Oblimin gamma                                      0
  Rotation algorithm (rstarts)                GPA (30)
  Standardized metric                             TRUE
  Row weights                                     None

                                                  Used       Total
  Number of observations                           927         972
  Number of missing patterns                       131            

Fit measures:
                    aic      bic    sabic    chisq df pvalue   cfi rmsea
  nfactors = 1 43069.53 43243.48 43129.15 1808.194 54      0 0.758 0.213

Eigenvalues correlation matrix:

    ev1     ev2     ev3     ev4     ev5     ev6     ev7     ev8     ev9    ev10 
  7.187   1.201   0.974   0.577   0.451   0.361   0.322   0.251   0.232   0.198 
   ev11    ev12 
  0.136   0.111 

Standardized loadings: (* = significant at 1% level)

           f1       unique.var   communalities
k29_1   0.705*           0.503           0.497
k29_2   0.820*           0.328           0.672
k29_3   0.559*           0.687           0.313
k29_4   0.669*           0.553           0.447
k29_5   0.637*           0.595           0.405
k29_6   0.888*           0.211           0.789
k29_7   0.837*           0.299           0.701
k29_8   0.821*           0.326           0.674
k29_9   0.773*           0.402           0.598
k29_10  0.786*           0.382           0.618
k29_11  0.731*           0.466           0.534
k29_12  0.720*           0.482           0.518

                           f1
Sum of squared loadings 6.767
Proportion of total     1.000
Proportion var          0.564
Cumulative var          0.564</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<details>
<summary>EFA-malli B</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>efa.malli.B <span class="ot">&lt;-</span> data.valitut <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">efa</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">nfactors =</span> <span class="dv">4</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">rotation =</span> <span class="st">"oblimin"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimator =</span> <span class="st">"ML"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.B <span class="ot">&lt;-</span> <span class="fu">summary</span>(</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  efa.malli.B,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ci =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">efa =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">cutoff =</span> <span class="dv">0</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.B</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>This is lavaan 0.6-18 -- running exploratory factor analysis

  Estimator                                         ML
  Rotation method                      OBLIMIN OBLIQUE
  Oblimin gamma                                      0
  Rotation algorithm (rstarts)                GPA (30)
  Standardized metric                             TRUE
  Row weights                                     None

                                                  Used       Total
  Number of observations                           927         972
  Number of missing patterns                       131            

Fit measures:
                    aic      bic    sabic   chisq df pvalue  cfi rmsea
  nfactors = 4 41529.07 41847.98 41638.37 207.737 24      0 0.98 0.141

Eigenvalues correlation matrix:

    ev1     ev2     ev3     ev4     ev5     ev6     ev7     ev8     ev9    ev10 
  7.187   1.201   0.974   0.577   0.451   0.361   0.322   0.251   0.232   0.198 
   ev11    ev12 
  0.136   0.111 

Standardized loadings: (* = significant at 1% level)

           f1      f2      f3      f4       unique.var   communalities
k29_1   0.378*  0.178*  0.013   0.500*           0.316           0.684
k29_2   0.490   0.082   0.530   0.053            0.158           0.842
k29_3  -0.032   0.668*  0.041   0.033            0.504           0.496
k29_4   0.103*  0.846* -0.028   0.013            0.242           0.758
k29_5  -0.106*  0.858*  0.048  -0.006            0.259           0.741
k29_6   0.119   0.052   0.791*  0.054            0.174           0.826
k29_7  -0.011   0.070   0.906* -0.086*           0.194           0.806
k29_8   0.069  -0.031   0.748*  0.117*           0.310           0.690
k29_9  -0.143   0.065   0.805*  0.024            0.317           0.683
k29_10 -0.054  -0.019   0.558*  0.377*           0.336           0.664
k29_11 -0.045  -0.035   0.073   0.942*           0.083           0.917
k29_12  0.022   0.082* -0.039   0.897*           0.148           0.852

                              f3    f4    f2    f1 total
Sum of sq (obliq) loadings 3.691 2.461 2.193 0.614 8.959
Proportion of total        0.412 0.275 0.245 0.069 1.000
Proportion var             0.308 0.205 0.183 0.051 0.747
Cumulative var             0.308 0.513 0.695 0.747 0.747

Factor correlations: (* = significant at 1% level)

       f1      f2      f3      f4 
f1  1.000                         
f2  0.299   1.000                 
f3  0.337   0.657*  1.000         
f4  0.311   0.495*  0.618*  1.000 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Molemmat mallit sopivat huonosti. Malli A:n sopivuusarvot ovat: <span class="math inline">\(\text{RMSEA} = 0.213, \text{CFI} = .758\)</span>. Malli B:n sopivuusarvot ovat: <span class="math inline">\(\text{RMSEA} = 0.141, \text{CFI} = .980\)</span>. AIC- ja BIC-arvot paranevat jonkin verran Malli B:ssä, mutta eivät suuresti.</p>
<p>Malli A kattaa yhteensä 56,4 prosenttia varianssista. Malli B kattaa 74,7 prosenttia varianssista.</p>
<p>Malli A:ssa kaikki muuttujat lataavat merkitsevästi positiivisesti faktoriin. Lataukset ovat suhteellisen samankokoisia (<span class="math inline">\(0.637-0.888\)</span>).</p>
<p>Malli B:ssä kaikki muuttujat paitsi <code>k29_2</code> lataavat merkitsevästi vähintään yhteen faktoriin. Lataukset ovat kuitenkin erisuuntaisia:</p>
<ul>
<li>Muuttuja <code>k29_1</code> lataa positiivisesti faktoreihin <code>f1</code>, <code>f2</code> ja <code>f4</code>, joista suurin lataus on viimeisellä faktorilla.</li>
<li>Muuttuja <code>k29_3</code> lataa positiivisesti faktoriin <code>f2</code>, eikä lataa muihin faktoreihin merkitsevästi.</li>
<li>Muuttuja <code>k29_4</code> lataa positiivisesti faktoreihin <code>f1</code> ja <code>f2</code>.</li>
<li>Muuttuja <code>k29_5</code> lataa positiivisesti faktoriin <code>f2</code> ja negatiivisesti faktoriin <code>f1</code></li>
<li>Muuttujat <code>k29_6</code> sekä <code>k29_9</code> lataavat positiivisesti faktoriin <code>f3</code>, eivätkä lataa muihin faktoreihin merkitsevästi.</li>
<li>Muuttuja <code>k29_7</code> lataa positiivisesti faktoriin <code>f3</code> ja negatiivisesti faktoriin <code>f4</code>.</li>
<li>Muuttujat <code>k29_8</code> sekä <code>k29_10</code> lataavat positiivisesti faktoreihin <code>f3</code> ja <code>f4</code>.</li>
<li>Muuttuja <code>k29_11</code> lataa positiivisesti faktoriin <code>f4</code>, eikä lataa muihin faktoreihin merkitsevästi.</li>
<li>Muuttuja <code>k29_12</code> lataa positiivisesti faktoreihin <code>f2</code> ja <code>f4</code>.</li>
</ul>
<p>Faktorit <code>f2-f4</code> edustavat suhteellisen suuria varianssiosuuksia (<span class="math inline">\(18.3-30.8 \%\)</span>). Faktori <code>f1</code> edustaa pienempää <span class="math inline">\(5.1 \%\)</span> varianssista.</p>
<p>Kaikki faktorit korreloivat positiivisesti toistensa kanssa, mutta faktorin <code>f1</code> korrelaatiot eivät ole merkitseviä 1 prosentin tasolla.</p>
<p>Faktori <code>f1</code> näyttäisi olevan tilastollinen artefakti: faktorille ei löydy selkeää tulkintaa, siihen lataa vain harva muuttuja, ja se kattaa vain pienen osan kaikesta vaihtelusta.</p>
<p>Faktori <code>f2</code> näyttäisi liittyvän turvallisen henkilöstön valintoihin. Siihen lataa suuresti turvallisuusselvitykset, alaikäisten koskettomattomuuden turvaaminen sekä rikostaustojen tarkistaminen.</p>
<p>Faktori <code>f3</code> näyttäisi liittyvän organisaatiotukeen epäasiallisen ja väkivaltaisen kohtelun kokemuksissa. Siihen lataa suuresti erilaiset toiminta- ja jatkotoimiohjeet kohtelutilanteissa sekä kohtelun raportointijärjestelmät.</p>
<p>Faktori <code>f4</code> näytäisi liittyvän tasa-arvoon ja yhdenvertaisuuteen tähtääviin toimenpiteisiin. Siihen lataa selkeimmin keskustelu- ja infotilaisuudet yhdenvertaisuuteen liittyen, mutta myös pienemmissä määrin koulutus sekä ilmoitusjärjestelmät.</p>
</section>
<section id="cfa-mallien-asettamista" class="level2" data-number="32.4">
<h2 data-number="32.4" class="anchored" data-anchor-id="cfa-mallien-asettamista"><span class="header-section-number">32.4</span> CFA-mallien asettamista</h2>
<p>Aloitimme asettamalla kaksi CFA-mallia, peilaten tuloksia EFA-malleista A ja B.</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cfa.malli.A <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_1 + k29_3 + k29_4 + k29_5 + k29_6 + k29_7 + k29_8 + k29_9 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>malli.A <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.A,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_12),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.A, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-18 ended normally after 45 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        33

                                                  Used       Total
  Number of observations                           925         972
  Number of missing patterns                       123            

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                              1652.603    1104.555
  Degrees of freedom                                44          44
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  1.496
    Yuan-Bentler correction (Mplus variant)                       

Model Test Baseline Model:

  Test statistic                              6397.102    4228.434
  Degrees of freedom                                55          55
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.513

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.746       0.746
  Tucker-Lewis Index (TLI)                       0.683       0.682
                                                                  
  Robust Comparative Fit Index (CFI)                         0.748
  Robust Tucker-Lewis Index (TLI)                            0.685

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -19779.442  -19779.442
  Scaling correction factor                                  1.088
      for the MLR correction                                      
  Loglikelihood unrestricted model (H1)     -18953.141  -18953.141
  Scaling correction factor                                  1.321
      for the MLR correction                                      
                                                                  
  Akaike (AIC)                               39624.884   39624.884
  Bayesian (BIC)                             39784.267   39784.267
  Sample-size adjusted Bayesian (SABIC)      39679.463   39679.463

Root Mean Square Error of Approximation:

  RMSEA                                          0.199       0.161
  90 Percent confidence interval - lower         0.191       0.155
  90 Percent confidence interval - upper         0.207       0.168
  P-value H_0: RMSEA &lt;= 0.050                    0.000       0.000
  P-value H_0: RMSEA &gt;= 0.080                    1.000       1.000
                                                                  
  Robust RMSEA                                               0.224
  90 Percent confidence interval - lower                     0.213
  90 Percent confidence interval - upper                     0.235
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.086       0.086

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
  f1 =~                                                                 
    k29_1             1.000                               1.000    1.000
    k29_3             0.842    0.053   15.811    0.000    0.737    0.946
    k29_4             0.941    0.053   17.715    0.000    0.837    1.046
    k29_5             0.906    0.057   15.813    0.000    0.794    1.019
    k29_6             1.156    0.058   19.910    0.000    1.042    1.270
    k29_7             1.068    0.061   17.505    0.000    0.948    1.188
    k29_8             1.090    0.056   19.395    0.000    0.980    1.200
    k29_9             1.010    0.060   16.838    0.000    0.892    1.128
    k29_10            1.091    0.053   20.434    0.000    0.986    1.196
    k29_11            1.075    0.045   23.732    0.000    0.986    1.164
    k29_12            1.036    0.044   23.786    0.000    0.951    1.122
   Std.lv  Std.all
                  
    2.064    0.683
    1.737    0.568
    1.943    0.668
    1.870    0.643
    2.386    0.877
    2.204    0.834
    2.249    0.817
    2.084    0.783
    2.252    0.792
    2.218    0.738
    2.138    0.722

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_1             4.739    0.102   46.650    0.000    4.540    4.938
   .k29_3             6.110    0.105   58.283    0.000    5.904    6.315
   .k29_4             6.425    0.103   62.636    0.000    6.223    6.626
   .k29_5             6.848    0.103   66.736    0.000    6.647    7.049
   .k29_6             6.367    0.094   67.937    0.000    6.183    6.550
   .k29_7             6.784    0.092   73.874    0.000    6.604    6.964
   .k29_8             6.653    0.095   69.752    0.000    6.466    6.840
   .k29_9             6.950    0.093   74.715    0.000    6.768    7.132
   .k29_10            6.185    0.098   63.379    0.000    5.994    6.377
   .k29_11            5.055    0.103   49.076    0.000    4.853    5.257
   .k29_12            4.928    0.101   48.690    0.000    4.730    5.126
   Std.lv  Std.all
    4.739    1.569
    6.110    1.997
    6.425    2.210
    6.848    2.353
    6.367    2.341
    6.784    2.567
    6.653    2.416
    6.950    2.610
    6.185    2.177
    5.055    1.682
    4.928    1.665

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_1             4.861    0.324   15.004    0.000    4.226    5.496
   .k29_3             6.342    0.326   19.441    0.000    5.703    6.981
   .k29_4             4.677    0.302   15.496    0.000    4.086    5.269
   .k29_5             4.973    0.314   15.831    0.000    4.357    5.589
   .k29_6             1.707    0.151   11.286    0.000    1.411    2.004
   .k29_7             2.125    0.185   11.501    0.000    1.763    2.487
   .k29_8             2.525    0.171   14.781    0.000    2.190    2.860
   .k29_9             2.748    0.181   15.163    0.000    2.392    3.103
   .k29_10            3.004    0.245   12.267    0.000    2.524    3.484
   .k29_11            4.117    0.299   13.762    0.000    3.530    4.703
   .k29_12            4.188    0.285   14.680    0.000    3.629    4.747
    f1                4.258    0.386   11.019    0.000    3.501    5.016
   Std.lv  Std.all
    4.861    0.533
    6.342    0.678
    4.677    0.553
    4.973    0.587
    1.707    0.231
    2.125    0.304
    2.525    0.333
    2.748    0.387
    3.004    0.372
    4.117    0.456
    4.188    0.478
    1.000    1.000</code></pre>
</div>
</div>
<p>Malli A sopii hyvin huonosti aineistoon. Robusti RMSEA on <span class="math inline">\(0.224\)</span> ja robusti CFI on <span class="math inline">\(0.748\)</span>, mitkä ovat molemmat reilusti yleisesti hyväksyttävien raja-arvojen ulkopuolella. Robusti SRMR on hieman parempi <span class="math inline">\(0.086\)</span>, joskin sekin raja-arvon ulkopuolella.</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>cfa.malli.B <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_3 + k29_4 + k29_5</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 =~ k29_6 + k29_7 + k29_8 + k29_9 + k29_10</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="st">              f3 =~ k29_1 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="st">              # faktorikorrelaatiot</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f2</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 ~~ f3</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f3</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>malli.B <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.B,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_12),</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.B, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-18 ended normally after 71 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        37

                                                  Used       Total
  Number of observations                           925         972
  Number of missing patterns                       123            

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                               383.262     272.914
  Degrees of freedom                                40          40
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  1.404
    Yuan-Bentler correction (Mplus variant)                       

Model Test Baseline Model:

  Test statistic                              6397.102    4228.434
  Degrees of freedom                                55          55
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.513

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.946       0.944
  Tucker-Lewis Index (TLI)                       0.926       0.923
                                                                  
  Robust Comparative Fit Index (CFI)                         0.950
  Robust Tucker-Lewis Index (TLI)                            0.932

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -19144.771  -19144.771
  Scaling correction factor                                  1.232
      for the MLR correction                                      
  Loglikelihood unrestricted model (H1)     -18953.141  -18953.141
  Scaling correction factor                                  1.321
      for the MLR correction                                      
                                                                  
  Akaike (AIC)                               38363.543   38363.543
  Bayesian (BIC)                             38542.245   38542.245
  Sample-size adjusted Bayesian (SABIC)      38424.737   38424.737

Root Mean Square Error of Approximation:

  RMSEA                                          0.096       0.079
  90 Percent confidence interval - lower         0.088       0.072
  90 Percent confidence interval - upper         0.105       0.087
  P-value H_0: RMSEA &lt;= 0.050                    0.000       0.000
  P-value H_0: RMSEA &gt;= 0.080                    0.999       0.453
                                                                  
  Robust RMSEA                                               0.104
  90 Percent confidence interval - lower                     0.093
  90 Percent confidence interval - upper                     0.116
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.044       0.044

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
  f1 =~                                                                 
    k29_3             1.000                               1.000    1.000
    k29_4             1.156    0.060   19.403    0.000    1.039    1.273
    k29_5             1.147    0.055   21.051    0.000    1.041    1.254
  f2 =~                                                                 
    k29_6             1.000                               1.000    1.000
    k29_7             0.952    0.024   40.038    0.000    0.905    0.998
    k29_8             0.923    0.028   32.736    0.000    0.868    0.978
    k29_9             0.864    0.034   25.545    0.000    0.798    0.930
    k29_10            0.603    0.053   11.421    0.000    0.500    0.707
  f3 =~                                                                 
    k29_1             1.000                               1.000    1.000
    k29_10            0.457    0.058    7.880    0.000    0.344    0.571
    k29_11            1.315    0.052   25.266    0.000    1.213    1.417
    k29_12            1.283    0.049   26.389    0.000    1.187    1.378
   Std.lv  Std.all
                  
    2.169    0.707
    2.508    0.858
    2.489    0.849
                  
    2.468    0.906
    2.349    0.884
    2.278    0.827
    2.132    0.800
    1.489    0.523
                  
    2.175    0.724
    0.995    0.350
    2.861    0.943
    2.790    0.927

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
  f1 ~~                                                                 
    f2                3.783    0.291   13.020    0.000    3.213    4.352
  f2 ~~                                                                 
    f3                3.625    0.277   13.078    0.000    3.082    4.168
  f1 ~~                                                                 
    f3                2.621    0.272    9.631    0.000    2.087    3.154
   Std.lv  Std.all
                  
    0.707    0.707
                  
    0.675    0.675
                  
    0.555    0.555

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_3             6.100    0.105   58.111    0.000    5.894    6.305
   .k29_4             6.401    0.102   62.699    0.000    6.201    6.602
   .k29_5             6.819    0.103   66.429    0.000    6.618    7.020
   .k29_6             6.367    0.094   67.995    0.000    6.183    6.550
   .k29_7             6.780    0.092   73.748    0.000    6.600    6.961
   .k29_8             6.657    0.095   69.824    0.000    6.470    6.844
   .k29_9             6.952    0.093   74.831    0.000    6.770    7.134
   .k29_10            6.178    0.098   63.066    0.000    5.986    6.370
   .k29_1             4.726    0.101   46.560    0.000    4.527    4.925
   .k29_11            4.965    0.104   47.956    0.000    4.762    5.168
   .k29_12            4.801    0.102   46.966    0.000    4.601    5.001
   Std.lv  Std.all
    6.100    1.987
    6.401    2.190
    6.819    2.327
    6.367    2.336
    6.780    2.552
    6.657    2.415
    6.952    2.609
    6.178    2.171
    4.726    1.573
    4.965    1.636
    4.801    1.596

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_3             4.716    0.352   13.398    0.000    4.026    5.406
   .k29_4             2.257    0.276    8.188    0.000    1.717    2.797
   .k29_5             2.391    0.256    9.331    0.000    1.889    2.893
   .k29_6             1.337    0.147    9.071    0.000    1.048    1.626
   .k29_7             1.542    0.153   10.068    0.000    1.242    1.842
   .k29_8             2.407    0.190   12.663    0.000    2.034    2.779
   .k29_9             2.557    0.188   13.637    0.000    2.189    2.924
   .k29_10            2.892    0.221   13.097    0.000    2.459    3.324
   .k29_1             4.291    0.307   13.992    0.000    3.690    4.892
   .k29_11            1.021    0.154    6.647    0.000    0.720    1.322
   .k29_12            1.266    0.158    7.996    0.000    0.956    1.576
    f1                4.704    0.418   11.253    0.000    3.885    5.523
    f2                6.092    0.343   17.756    0.000    5.419    6.764
    f3                4.732    0.378   12.530    0.000    3.992    5.473
   Std.lv  Std.all
    4.716    0.501
    2.257    0.264
    2.391    0.279
    1.337    0.180
    1.542    0.219
    2.407    0.317
    2.557    0.360
    2.892    0.357
    4.291    0.476
    1.021    0.111
    1.266    0.140
    1.000    1.000
    1.000    1.000
    1.000    1.000</code></pre>
</div>
</div>
<p>Malli B sopii jossain määrin aineistoon. Robusti RMSEA on <span class="math inline">\(0.104\)</span>, mikä on raja-arvon ulkopuolella. Robusti CFI on <span class="math inline">\(0.950\)</span>, mikä on juuri raja-arvolla. Robusti SRMR on <span class="math inline">\(.044\)</span>, mikä on hyväksyttävissä rajoissa.</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>vrt <span class="ot">&lt;-</span> <span class="fu">compareFit</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  malli.B,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  malli.A,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">nested =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">moreIndices =</span> <span class="cn">TRUE</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vrt)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>####################### Model Fit Indices ###########################
        chisq.scaled df.scaled pvalue.scaled rmsea.robust cfi.robust tli.robust
malli.B     272.914†        40          .000        .104†      .950†      .932†
malli.A    1104.555         44          .000        .224       .748       .685 
         srmr        aic        bic
malli.B .044† 38363.543† 38542.245†
malli.A .086  39624.884  39784.267 </code></pre>
</div>
</div>
<p>Mallien vertailu osoittaa selkeästi, että Malli B sopii aineistoon paremmin kaikilla mittareilla.</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(malli.B) <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mi)) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(op <span class="sc">==</span> <span class="st">"=~"</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   lhs op    rhs     mi    epc sepc.lv sepc.all sepc.nox
1   f1 =~  k29_1 50.689  0.342   0.741    0.247    0.247
2   f3 =~  k29_7 35.391 -0.219  -0.477   -0.180   -0.180
3   f2 =~  k29_1 30.509  0.258   0.637    0.212    0.212
4   f1 =~ k29_11 18.921 -0.157  -0.340   -0.112   -0.112
5   f3 =~  k29_8 13.886  0.156   0.339    0.123    0.123
6   f2 =~ k29_12 10.151 -0.122  -0.300   -0.100   -0.100
7   f3 =~  k29_6  8.083  0.105   0.228    0.084    0.084
8   f1 =~  k29_8  3.298 -0.085  -0.184   -0.067   -0.067
9   f3 =~  k29_5  3.235 -0.084  -0.184   -0.063   -0.063
10  f1 =~ k29_10  2.501 -0.077  -0.168   -0.059   -0.059
11  f1 =~  k29_6  1.605  0.052   0.112    0.041    0.041
12  f3 =~  k29_4  1.061  0.048   0.105    0.036    0.036
13  f3 =~  k29_3  0.915  0.049   0.107    0.035    0.035
14  f1 =~  k29_9  0.835  0.043   0.094    0.035    0.035
15  f2 =~  k29_3  0.708  0.048   0.119    0.039    0.039
16  f2 =~  k29_5  0.649 -0.046  -0.115   -0.039   -0.039
17  f1 =~ k29_12  0.497  0.025   0.055    0.018    0.018
18  f2 =~ k29_11  0.109 -0.013  -0.032   -0.010   -0.010
19  f1 =~  k29_7  0.105  0.013   0.029    0.011    0.011
20  f3 =~  k29_9  0.081 -0.012  -0.026   -0.010   -0.010
21  f2 =~  k29_4  0.004  0.004   0.009    0.003    0.003</code></pre>
</div>
</div>
<p>Malli B:ssä suurimmat indeksimuutokset koskevat muuttujaa <code>k29_1</code>. Sen vapauttaminen kaikille faktoreille aiheuttaisi <span class="math inline">\(50.7\)</span> (<code>f1</code>) ja <span class="math inline">\(30.5\)</span> (<code>f2</code>) laskun khii neliö -indeksissä. Odotetut faktorilatausarvot pieniä ovat <span class="math inline">\(\text{F1} = .247, \text{F2} = .212\)</span>.</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(malli.B) <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mi)) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(op <span class="sc">==</span> <span class="st">"~~"</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      lhs op    rhs     mi    epc sepc.lv sepc.all sepc.nox
1   k29_6 ~~  k29_9 71.480 -0.816  -0.816   -0.441   -0.441
2   k29_9 ~~ k29_10 71.391  0.922   0.922    0.339    0.339
3   k29_7 ~~ k29_10 42.513 -0.616  -0.616   -0.292   -0.292
4   k29_6 ~~  k29_7 35.446  0.570   0.570    0.397    0.397
5   k29_4 ~~  k29_1 28.237  0.764   0.764    0.245    0.245
6   k29_7 ~~  k29_9 22.254  0.450   0.450    0.227    0.227
7  k29_11 ~~ k29_12 20.138  1.221   1.221    1.075    1.075
8   k29_1 ~~ k29_11 17.343 -0.626  -0.626   -0.299   -0.299
9   k29_8 ~~ k29_10 16.177  0.434   0.434    0.164    0.164
10 k29_10 ~~ k29_11 12.316  0.357   0.357    0.208    0.208
11  k29_7 ~~  k29_8 12.130 -0.337  -0.337   -0.175   -0.175
12  k29_3 ~~  k29_9  9.243  0.425   0.425    0.122    0.122
13  k29_4 ~~ k29_11  8.408 -0.273  -0.273   -0.180   -0.180
14  k29_3 ~~  k29_1  8.181  0.513   0.513    0.114    0.114
15  k29_5 ~~  k29_1  7.674 -0.404  -0.404   -0.126   -0.126
16 k29_10 ~~ k29_12  7.474 -0.275  -0.275   -0.144   -0.144
17  k29_6 ~~ k29_10  7.050 -0.250  -0.250   -0.127   -0.127
18  k29_6 ~~  k29_1  6.610  0.274   0.274    0.115    0.115
19  k29_4 ~~  k29_6  5.761  0.223   0.223    0.128    0.128
20  k29_7 ~~ k29_12  4.343 -0.151  -0.151   -0.108   -0.108
21  k29_9 ~~ k29_12  3.963 -0.173  -0.173   -0.096   -0.096
22  k29_8 ~~ k29_12  3.834  0.167   0.167    0.096    0.096
23  k29_4 ~~  k29_9  3.615 -0.214  -0.214   -0.089   -0.089
24  k29_9 ~~  k29_1  2.661 -0.214  -0.214   -0.065   -0.065
25  k29_3 ~~  k29_6  2.575 -0.184  -0.184   -0.073   -0.073
26  k29_4 ~~  k29_8  2.494 -0.175  -0.175   -0.075   -0.075
27  k29_5 ~~ k29_12  1.636  0.124   0.124    0.071    0.071
28  k29_3 ~~  k29_4  1.458 -0.261  -0.261   -0.080   -0.080
29  k29_6 ~~  k29_8  1.392  0.116   0.116    0.065    0.065
30 k29_10 ~~  k29_1  1.361 -0.160  -0.160   -0.045   -0.045
31  k29_3 ~~ k29_10  1.218 -0.161  -0.161   -0.044   -0.044
32  k29_4 ~~ k29_12  1.169  0.103   0.103    0.061    0.061
33  k29_8 ~~  k29_9  1.167 -0.115  -0.115   -0.046   -0.046
34  k29_4 ~~  k29_5  0.927  0.268   0.268    0.116    0.116
35  k29_8 ~~ k29_11  0.899 -0.079  -0.079   -0.051   -0.051
36  k29_1 ~~ k29_12  0.775  0.129   0.129    0.055    0.055
37  k29_8 ~~  k29_1  0.622  0.101   0.101    0.032    0.032
38  k29_6 ~~ k29_11  0.614  0.055   0.055    0.047    0.047
39  k29_3 ~~  k29_7  0.611  0.092   0.092    0.034    0.034
40  k29_5 ~~ k29_11  0.560 -0.071  -0.071   -0.046   -0.046
41  k29_3 ~~ k29_11  0.467 -0.080  -0.080   -0.036   -0.036
42  k29_5 ~~  k29_9  0.426  0.074   0.074    0.030    0.030
43  k29_4 ~~ k29_10  0.402 -0.074  -0.074   -0.029   -0.029
44  k29_3 ~~  k29_8  0.350 -0.081  -0.081   -0.024   -0.024
45  k29_5 ~~  k29_6  0.342 -0.055  -0.055   -0.031   -0.031
46  k29_5 ~~  k29_7  0.195  0.042   0.042    0.022    0.022
47  k29_3 ~~  k29_5  0.124  0.075   0.075    0.022    0.022
48  k29_7 ~~  k29_1  0.054  0.025   0.025    0.010    0.010
49  k29_9 ~~ k29_11  0.027  0.014   0.014    0.009    0.009
50  k29_5 ~~  k29_8  0.027 -0.018  -0.018   -0.008   -0.008
51  k29_6 ~~ k29_12  0.022  0.010   0.010    0.008    0.008
52  k29_4 ~~  k29_7  0.016  0.012   0.012    0.006    0.006
53  k29_7 ~~ k29_11  0.009  0.007   0.007    0.005    0.005
54  k29_3 ~~ k29_12  0.001 -0.004  -0.004   -0.001   -0.001
55  k29_5 ~~ k29_10  0.001 -0.003  -0.003   -0.001   -0.001</code></pre>
</div>
</div>
<p>Virhekorrelaatioiden modifikaatioindeksit osoittavat kuitenkin suurempia ongelmia. Suurimmat modifikaatioindeksit löytyvät pääsääntöisesti faktorin <code>f2</code> muuttujilta <code>k29_6</code>, <code>k29_7</code>, <code>k29_9</code> ja <code>k29_10</code>. Varsinkin muuttujien <code>k29_9</code> ja <code>k29_10</code> virheen vapauttaminen antaisi odotetusti jopa korrelaation <code>0.922</code>, eli erittäin suuren korrelaation.</p>
<p>Onkin huomattava, että muuttuja <code>k29_8</code> <em>ei</em> nouse suurimpien modifikaatioindeksien ryhmään. Tämä voisi osoittaa, että muuttuja käytännössä kaappaa faktorivarianssin, jolloin muut muuttujat eivät pääse lataamaan vapaasti faktoriin <code>f2</code>.</p>
<p>Kokeilimme siksi mallia, jossa jätimme pois muuttujan <code>k29_8</code> kokonaan (Malli C).</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>cfa.malli.C <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_3 + k29_4 + k29_5</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 =~ k29_6 + k29_7 + k29_9 + k29_10</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="st">              f3 =~ k29_1 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="st">              # faktorikorrelaatiot</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f2</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 ~~ f3</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f3</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>malli.C <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.C,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_7, k29_9<span class="sc">:</span>k29_12),</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.C, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-18 ended normally after 71 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        34

                                                  Used       Total
  Number of observations                           923         972
  Number of missing patterns                       112            

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                               331.191     238.734
  Degrees of freedom                                31          31
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  1.387
    Yuan-Bentler correction (Mplus variant)                       

Model Test Baseline Model:

  Test statistic                              5590.414    3661.219
  Degrees of freedom                                45          45
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.527

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.946       0.943
  Tucker-Lewis Index (TLI)                       0.921       0.917
                                                                  
  Robust Comparative Fit Index (CFI)                         0.950
  Robust Tucker-Lewis Index (TLI)                            0.927

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -17493.558  -17493.558
  Scaling correction factor                                  1.248
      for the MLR correction                                      
  Loglikelihood unrestricted model (H1)     -17327.962  -17327.962
  Scaling correction factor                                  1.314
      for the MLR correction                                      
                                                                  
  Akaike (AIC)                               35055.116   35055.116
  Bayesian (BIC)                             35219.255   35219.255
  Sample-size adjusted Bayesian (SABIC)      35111.275   35111.275

Root Mean Square Error of Approximation:

  RMSEA                                          0.102       0.085
  90 Percent confidence interval - lower         0.093       0.077
  90 Percent confidence interval - upper         0.113       0.094
  P-value H_0: RMSEA &lt;= 0.050                    0.000       0.000
  P-value H_0: RMSEA &gt;= 0.080                    1.000       0.848
                                                                  
  Robust RMSEA                                               0.111
  90 Percent confidence interval - lower                     0.098
  90 Percent confidence interval - upper                     0.125
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.045       0.045

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
  f1 =~                                                                 
    k29_3             1.000                               1.000    1.000
    k29_4             1.158    0.060   19.338    0.000    1.041    1.276
    k29_5             1.143    0.055   20.856    0.000    1.036    1.250
  f2 =~                                                                 
    k29_6             1.000                               1.000    1.000
    k29_7             0.975    0.026   37.205    0.000    0.924    1.027
    k29_9             0.876    0.037   23.673    0.000    0.803    0.948
    k29_10            0.564    0.052   10.859    0.000    0.462    0.666
  f3 =~                                                                 
    k29_1             1.000                               1.000    1.000
    k29_10            0.502    0.057    8.799    0.000    0.390    0.614
    k29_11            1.315    0.052   25.228    0.000    1.213    1.417
    k29_12            1.281    0.049   26.347    0.000    1.186    1.377
   Std.lv  Std.all
                  
    2.165    0.706
    2.507    0.859
    2.474    0.846
                  
    2.430    0.898
    2.370    0.897
    2.128    0.802
    1.371    0.485
                  
    2.168    0.722
    1.088    0.385
    2.851    0.943
    2.778    0.927

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
  f1 ~~                                                                 
    f2                3.732    0.288   12.960    0.000    3.168    4.297
  f2 ~~                                                                 
    f3                3.413    0.278   12.296    0.000    2.869    3.958
  f1 ~~                                                                 
    f3                2.593    0.271    9.575    0.000    2.063    3.124
   Std.lv  Std.all
                  
    0.709    0.709
                  
    0.648    0.648
                  
    0.553    0.553

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_3             6.103    0.105   58.183    0.000    5.898    6.309
   .k29_4             6.407    0.102   62.902    0.000    6.208    6.607
   .k29_5             6.826    0.102   66.659    0.000    6.625    7.027
   .k29_6             6.388    0.093   68.543    0.000    6.205    6.571
   .k29_7             6.796    0.091   74.310    0.000    6.616    6.975
   .k29_9             6.965    0.092   75.326    0.000    6.784    7.146
   .k29_10            6.200    0.097   63.636    0.000    6.009    6.391
   .k29_1             4.731    0.102   46.607    0.000    4.532    4.930
   .k29_11            4.978    0.103   48.154    0.000    4.775    5.180
   .k29_12            4.814    0.102   47.159    0.000    4.614    5.014
   Std.lv  Std.all
    6.103    1.990
    6.407    2.196
    6.826    2.335
    6.388    2.360
    6.796    2.573
    6.965    2.626
    6.200    2.195
    4.731    1.577
    4.978    1.646
    4.814    1.606

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_3             4.718    0.354   13.340    0.000    4.024    5.411
   .k29_4             2.224    0.274    8.128    0.000    1.688    2.760
   .k29_5             2.427    0.259    9.360    0.000    1.918    2.935
   .k29_6             1.420    0.174    8.146    0.000    1.078    1.761
   .k29_7             1.360    0.155    8.788    0.000    1.057    1.664
   .k29_9             2.506    0.200   12.557    0.000    2.115    2.897
   .k29_10            2.984    0.220   13.581    0.000    2.553    3.415
   .k29_1             4.305    0.308   13.989    0.000    3.702    4.908
   .k29_11            1.017    0.154    6.614    0.000    0.716    1.318
   .k29_12            1.268    0.160    7.913    0.000    0.954    1.581
    f1                4.687    0.418   11.219    0.000    3.868    5.506
    f2                5.906    0.349   16.905    0.000    5.221    6.590
    f3                4.701    0.377   12.482    0.000    3.963    5.439
   Std.lv  Std.all
    4.718    0.502
    2.224    0.261
    2.427    0.284
    1.420    0.194
    1.360    0.195
    2.506    0.356
    2.984    0.374
    4.305    0.478
    1.017    0.111
    1.268    0.141
    1.000    1.000
    1.000    1.000
    1.000    1.000</code></pre>
</div>
</div>
<p>Mallin sopivuusarvot eivät muutu juuri ollenkaan. Robusti RMSEA on nyt lievästi heikompi <span class="math inline">\(0.111\)</span>, CFI on vielä <span class="math inline">\(0.950\)</span> ja SRMR on hivenen heikompi <span class="math inline">\(0.045\)</span>. Toisin sanoen, malli ei näytä parantuvan jättämällä muuttujan <code>k29_8</code> pois analyysista.</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(malli.C) <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mi)) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(op <span class="sc">==</span> <span class="st">"~~"</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      lhs op    rhs     mi    epc sepc.lv sepc.all sepc.nox
1   k29_6 ~~  k29_9 91.943 -1.111  -1.111   -0.589   -0.589
2   k29_9 ~~ k29_10 87.746  1.053   1.053    0.385    0.385
3   k29_7 ~~ k29_10 42.665 -0.658  -0.658   -0.327   -0.327
4   k29_6 ~~  k29_7 34.652  0.801   0.801    0.577    0.577
5   k29_4 ~~  k29_1 28.098  0.761   0.761    0.246    0.246
6  k29_11 ~~ k29_12 19.015  1.204   1.204    1.060    1.060
7   k29_1 ~~ k29_11 17.366 -0.633  -0.633   -0.302   -0.302
8   k29_7 ~~  k29_9 12.522  0.400   0.400    0.217    0.217
9  k29_10 ~~ k29_11 10.990  0.348   0.348    0.200    0.200
10  k29_4 ~~ k29_11  8.997 -0.282  -0.282   -0.187   -0.187
11  k29_3 ~~  k29_9  8.597  0.412   0.412    0.120    0.120
12  k29_3 ~~  k29_1  8.243  0.515   0.515    0.114    0.114
13  k29_6 ~~  k29_1  8.122  0.319   0.319    0.129    0.129
14  k29_5 ~~  k29_1  7.316 -0.396  -0.396   -0.122   -0.122
15 k29_10 ~~ k29_12  7.261 -0.280  -0.280   -0.144   -0.144
16  k29_4 ~~  k29_6  4.904  0.216   0.216    0.122    0.122
17  k29_4 ~~  k29_9  4.784 -0.247  -0.247   -0.105   -0.105
18  k29_3 ~~  k29_6  3.198 -0.215  -0.215   -0.083   -0.083
19  k29_9 ~~ k29_12  2.989 -0.151  -0.151   -0.085   -0.085
20  k29_9 ~~  k29_1  2.704 -0.217  -0.217   -0.066   -0.066
21  k29_7 ~~ k29_12  2.651 -0.118  -0.118   -0.090   -0.090
22  k29_3 ~~  k29_4  1.976 -0.303  -0.303   -0.094   -0.094
23  k29_5 ~~ k29_12  1.837  0.131   0.131    0.075    0.075
24  k29_3 ~~ k29_10  1.292 -0.169  -0.169   -0.045   -0.045
25  k29_4 ~~ k29_12  1.264  0.107   0.107    0.064    0.064
26  k29_4 ~~  k29_5  1.065  0.286   0.286    0.123    0.123
27  k29_1 ~~ k29_12  0.974  0.146   0.146    0.063    0.063
28 k29_10 ~~  k29_1  0.795 -0.125  -0.125   -0.035   -0.035
29  k29_6 ~~ k29_12  0.734  0.064   0.064    0.047    0.047
30  k29_5 ~~ k29_11  0.697 -0.080  -0.080   -0.051   -0.051
31  k29_3 ~~ k29_11  0.519 -0.084  -0.084   -0.038   -0.038
32  k29_6 ~~ k29_11  0.479  0.051   0.051    0.042    0.042
33  k29_4 ~~ k29_10  0.395 -0.075  -0.075   -0.029   -0.029
34  k29_5 ~~  k29_6  0.369 -0.060  -0.060   -0.032   -0.032
35  k29_3 ~~  k29_7  0.259  0.060   0.060    0.023    0.023
36  k29_4 ~~  k29_7  0.245 -0.047  -0.047   -0.027   -0.027
37  k29_3 ~~  k29_5  0.237  0.104   0.104    0.031    0.031
38  k29_5 ~~  k29_9  0.212  0.053   0.053    0.021    0.021
39  k29_6 ~~ k29_10  0.128 -0.037  -0.037   -0.018   -0.018
40  k29_7 ~~  k29_1  0.098  0.034   0.034    0.014    0.014
41  k29_5 ~~ k29_10  0.053  0.028   0.028    0.010    0.010
42  k29_9 ~~ k29_11  0.012  0.009   0.009    0.006    0.006
43  k29_5 ~~  k29_7  0.009  0.009   0.009    0.005    0.005
44  k29_3 ~~ k29_12  0.000  0.001   0.001    0.000    0.000
45  k29_7 ~~ k29_11  0.000  0.000   0.000    0.000    0.000</code></pre>
</div>
</div>
<p>Kokeilimme palauttaa muuttujan <code>k29_8</code> malliin ja vapauttamaan virhekorrelaatiot muuttujapareille <code>k29_6-k29_9</code>, <code>k29_9-k29_10</code> sekä <code>k29_7-k29_10</code> (Malli D).</p>
<div class="cell">
<details>
<summary>Koodi</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cfa.malli.D <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_3 + k29_4 + k29_5</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 =~ k29_6 + k29_7 + k29_8 + k29_9 + k29_10</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="st">              f3 =~ k29_1 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="st">              # faktorikorrelaatiot</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f2</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 ~~ f3</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f3</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="st">              # virhekorrelaatiot</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="st">              k29_6 ~~ k29_9</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="st">              k29_9 ~~ k29_10</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="st">              k29_7 ~~ k29_10</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>malli.D <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.D,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_12),</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.D, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-18 ended normally after 85 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        40

                                                  Used       Total
  Number of observations                           925         972
  Number of missing patterns                       123            

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                               230.653     167.639
  Degrees of freedom                                37          37
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  1.376
    Yuan-Bentler correction (Mplus variant)                       

Model Test Baseline Model:

  Test statistic                              6397.102    4228.434
  Degrees of freedom                                55          55
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.513

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.969       0.969
  Tucker-Lewis Index (TLI)                       0.955       0.953
                                                                  
  Robust Comparative Fit Index (CFI)                         0.972
  Robust Tucker-Lewis Index (TLI)                            0.958

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -19068.467  -19068.467
  Scaling correction factor                                  1.271
      for the MLR correction                                      
  Loglikelihood unrestricted model (H1)     -18953.141  -18953.141
  Scaling correction factor                                  1.321
      for the MLR correction                                      
                                                                  
  Akaike (AIC)                               38216.934   38216.934
  Bayesian (BIC)                             38410.126   38410.126
  Sample-size adjusted Bayesian (SABIC)      38283.090   38283.090

Root Mean Square Error of Approximation:

  RMSEA                                          0.075       0.062
  90 Percent confidence interval - lower         0.066       0.054
  90 Percent confidence interval - upper         0.085       0.070
  P-value H_0: RMSEA &lt;= 0.050                    0.000       0.008
  P-value H_0: RMSEA &gt;= 0.080                    0.208       0.000
                                                                  
  Robust RMSEA                                               0.082
  90 Percent confidence interval - lower                     0.069
  90 Percent confidence interval - upper                     0.095
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         0.608

Standardized Root Mean Square Residual:

  SRMR                                           0.042       0.042

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
  f1 =~                                                                 
    k29_3             1.000                               1.000    1.000
    k29_4             1.156    0.060   19.388    0.000    1.039    1.273
    k29_5             1.146    0.054   21.034    0.000    1.039    1.253
  f2 =~                                                                 
    k29_6             1.000                               1.000    1.000
    k29_7             0.941    0.024   39.699    0.000    0.894    0.987
    k29_8             0.893    0.028   31.431    0.000    0.837    0.949
    k29_9             0.870    0.032   27.159    0.000    0.807    0.932
    k29_10            0.591    0.058   10.197    0.000    0.478    0.705
  f3 =~                                                                 
    k29_1             1.000                               1.000    1.000
    k29_10            0.449    0.062    7.257    0.000    0.328    0.570
    k29_11            1.314    0.052   25.262    0.000    1.212    1.416
    k29_12            1.282    0.049   26.400    0.000    1.187    1.377
   Std.lv  Std.all
                  
    2.169    0.707
    2.508    0.858
    2.487    0.849
                  
    2.513    0.922
    2.364    0.889
    2.244    0.814
    2.185    0.820
    1.486    0.523
                  
    2.176    0.724
    0.977    0.344
    2.860    0.943
    2.790    0.927

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
  f1 ~~                                                                 
    f2                3.832    0.293   13.059    0.000    3.257    4.408
  f2 ~~                                                                 
    f3                3.653    0.277   13.181    0.000    3.110    4.197
  f1 ~~                                                                 
    f3                2.622    0.272    9.646    0.000    2.089    3.155
 .k29_6 ~~                                                              
   .k29_9            -0.559    0.114   -4.921    0.000   -0.782   -0.337
 .k29_9 ~~                                                              
   .k29_10            0.663    0.183    3.620    0.000    0.304    1.022
 .k29_7 ~~                                                              
   .k29_10           -0.415    0.126   -3.297    0.001   -0.661   -0.168
   Std.lv  Std.all
                  
    0.703    0.703
                  
    0.668    0.668
                  
    0.555    0.555
                  
   -0.559   -0.348
                  
    0.663    0.252
                  
   -0.415   -0.198

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_3             6.100    0.105   58.113    0.000    5.894    6.305
   .k29_4             6.401    0.102   62.718    0.000    6.201    6.601
   .k29_5             6.819    0.103   66.449    0.000    6.618    7.020
   .k29_6             6.365    0.094   67.969    0.000    6.181    6.548
   .k29_7             6.782    0.092   73.752    0.000    6.601    6.962
   .k29_8             6.660    0.095   69.932    0.000    6.473    6.846
   .k29_9             6.945    0.093   74.763    0.000    6.763    7.127
   .k29_10            6.178    0.098   63.153    0.000    5.986    6.370
   .k29_1             4.725    0.101   46.553    0.000    4.526    4.924
   .k29_11            4.966    0.103   47.984    0.000    4.763    5.169
   .k29_12            4.801    0.102   46.973    0.000    4.601    5.002
   Std.lv  Std.all
    6.100    1.987
    6.401    2.190
    6.819    2.328
    6.365    2.335
    6.782    2.552
    6.660    2.417
    6.945    2.607
    6.178    2.174
    4.725    1.573
    4.966    1.637
    4.801    1.596

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
   .k29_3             4.714    0.353   13.374    0.000    4.024    5.405
   .k29_4             2.251    0.275    8.179    0.000    1.712    2.791
   .k29_5             2.399    0.256    9.381    0.000    1.898    2.900
   .k29_6             1.114    0.149    7.488    0.000    0.822    1.405
   .k29_7             1.474    0.139   10.578    0.000    1.201    1.748
   .k29_8             2.555    0.194   13.181    0.000    2.175    2.935
   .k29_9             2.323    0.197   11.807    0.000    1.937    2.709
   .k29_10            2.976    0.229   13.021    0.000    2.528    3.424
   .k29_1             4.291    0.307   13.978    0.000    3.689    4.892
   .k29_11            1.022    0.154    6.655    0.000    0.721    1.323
   .k29_12            1.265    0.157    8.045    0.000    0.957    1.573
    f1                4.706    0.418   11.248    0.000    3.886    5.526
    f2                6.315    0.346   18.258    0.000    5.637    6.992
    f3                4.735    0.378   12.528    0.000    3.994    5.476
   Std.lv  Std.all
    4.714    0.500
    2.251    0.264
    2.399    0.280
    1.114    0.150
    1.474    0.209
    2.555    0.337
    2.323    0.327
    2.976    0.368
    4.291    0.475
    1.022    0.111
    1.265    0.140
    1.000    1.000
    1.000    1.000
    1.000    1.000</code></pre>
</div>
</div>
<p>Malli D sopii mallia B lievästi paremmin. Robusti RMSEA on nyt parantunut tasolle <span class="math inline">\(0.082\)</span>, CFI on parantunut tasolle <span class="math inline">\(0.972\)</span> ja SRMR on kuta kuinkin samalla tasolla, <span class="math inline">\(0.042\)</span>. Malli ei kuitenkaan vieläkään sovi kaikkien raja-arvojen sisällä.</p>
<p>Totesimme tässä vaiheessa, ettemme pysty asettamaan raja-arvojen mukaista mallia, ja hylkäsimme kaikki mallit.</p>
</section>
<section id="yhteenveto" class="level2" data-number="32.5">
<h2 data-number="32.5" class="anchored" data-anchor-id="yhteenveto"><span class="header-section-number">32.5</span> Yhteenveto</h2>
<p>Emme pystyneet asettamaan mallia, joka sopisi yleisesti hyväksyttyjen raja-arvojen puitteissa kaikilla indekseillä. Parhaiten sopiva malli on Malli D: kolmen faktorin malli, jossa kolme virhekorrelaatiota on vapautettu muuttujien <code>k29_6</code> (Ohjeet ahdistelutilanteiden käsittelyyn), <code>k29_7</code> (Ohjeet uhka- ja väkivaltatilanteen käsittelyyn), <code>k29_9</code> (Koulutus väkivaltatilanteiden kohtaamiselle) ja <code>k29_10</code> (Koulutus kohtelun tunnistamiselle) välillä.</p>
<p>Mallin epäsopivuudelle voi olla useita eri selityksiä. On mahdollista, että sovitamme väärää mallia aineistoon, ja että asenteet riippuvat todellisuudessa muista syistä. On myös mahdollista, että otantamme ei pysty tunnistamaan mallia vääristymien takia, tai että meiltä puuttuu jotain muuttujia, jotka paremmin kuvailisivat latentteja asennefaktoreita. Aineistossa voi myös olla vastaajia, joiden vastauskonfiguraatiot aiheuttavat joko vääriä positiiveja tai negatiiveja.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopioitu!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopioitu!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tayvkayttoonotto_validointi.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Toimintaohjelman käyttöönoton ryhmittelyanalyysi</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./muutosaie_sem.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Muutosaikeiden ennustaminen työuupumuksen ja kohtelun avulla</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Lähdekoodi</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb25" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Toimintaohjelmaan kohdistuvien asenteiden faktorianalyysi {#sec-tayvasenteet_validointi}</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>eval: true</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>Tässä osiossa tarkistamme toimintaohjelmaan kohdistuvien asenteiden faktorirakenteen.</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tayvasenteet_validointi-00-paketit</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HH) <span class="co"># VIF-arvon laskeminen</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EFAtools) <span class="co"># Datasopivuuden tarkastusfunktiot</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan) <span class="co"># EFA- ja CFA-mallien asettaminen</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semTools) <span class="co"># Mallien vertailufunktio</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tayvasenteet_validointi-01-avaaminen</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">"output/anonymisoitudata.csv"</span>, <span class="at">tryLogical =</span> <span class="cn">FALSE</span>)</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Muuttujien valitseminen malliin</span></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>Valitsimme kaikki 12 pelastustoimen tasa-arvon ja yhdenvertaisuuden toimintaohjelman tehokkuuden arvioinnin muuttujat mukaan analyysiin:</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_1`</span>: Tasa-arvo- tai yhdenvertaisuussuunnitelma</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_2`</span>: Toimintaohjeet epäasialliseen käytökseen, häirintään tai seksuaaliseen häirintään reagointiin</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_3`</span>: Henkilöstön turvallisuusselvitykset</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_4`</span>: Ohjeet alaikäisten koskemattomuuden turvaamiselle</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_5`</span>: Nuorten kanssa toimivien rikostaustojen tarkastaminen</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_6`</span>: Ohjeet ahdistelutilanteen käsittelyyn</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_7`</span>: Ohjeet uhka- ja väkivaltatilanteen käsittelyyn</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_8`</span>: Ilmoitusjärjestelmä epäasiallisen kohtelun raportoimiseksi</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_9`</span>: Koulutus uhka- ja väkivaltatilanteiden kohtaamiseen</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_10`</span>: Koulutus epäasiallisen kohtelun tunnistamiseen</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_11`</span>: Keskustelutilaisuuksia tasa-arvo- ja yhdenvertaisuusaiheista</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`k29_12`</span>: Henkilöstön infotilaisuudet organisaation yhdenvertaisuustilanteesta</span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a><span class="fu">## Datasopivuuden tarkastus</span></span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-52"><a href="#cb25-52" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-53"><a href="#cb25-53" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tayvasenteet_validointi-02-efasopivuustestit</span></span>
<span id="cb25-54"><a href="#cb25-54" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "EFA-mallin sopivuustestit"</span></span>
<span id="cb25-55"><a href="#cb25-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-56"><a href="#cb25-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Mahalanobiksen etäisyys ja merkitsevyys</span></span>
<span id="cb25-57"><a href="#cb25-57" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>mahalanobis <span class="ot">&lt;-</span> <span class="fu">mahalanobis</span>(</span>
<span id="cb25-58"><a href="#cb25-58" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12),</span>
<span id="cb25-59"><a href="#cb25-59" aria-hidden="true" tabindex="-1"></a>  <span class="at">center =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span> <span class="fu">colMeans</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-60"><a href="#cb25-60" aria-hidden="true" tabindex="-1"></a>  <span class="at">cov =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span> <span class="fu">cov</span>(<span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb25-61"><a href="#cb25-61" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-62"><a href="#cb25-62" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>mahalanobis.p <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-63"><a href="#cb25-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mahalanobis) <span class="sc">|&gt;</span></span>
<span id="cb25-64"><a href="#cb25-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>() <span class="sc">|&gt;</span></span>
<span id="cb25-65"><a href="#cb25-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.double</span>() <span class="sc">|&gt;</span></span>
<span id="cb25-66"><a href="#cb25-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pchisq</span>(</span>
<span id="cb25-67"><a href="#cb25-67" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> data <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span> <span class="fu">ncol</span>() <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb25-68"><a href="#cb25-68" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-69"><a href="#cb25-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-70"><a href="#cb25-70" aria-hidden="true" tabindex="-1"></a><span class="co"># Kerätään kaikki tulokset yhteen listaan</span></span>
<span id="cb25-71"><a href="#cb25-71" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb25-72"><a href="#cb25-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-73"><a href="#cb25-73" aria-hidden="true" tabindex="-1"></a><span class="co"># Mahalanobiksen pohjalta poistettavat vastaajat</span></span>
<span id="cb25-74"><a href="#cb25-74" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>poisto_n <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-75"><a href="#cb25-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mahalanobis.p <span class="sc">&lt;</span> .<span class="dv">001</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-76"><a href="#cb25-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb25-77"><a href="#cb25-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span>
<span id="cb25-78"><a href="#cb25-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-79"><a href="#cb25-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Bartlettin testi</span></span>
<span id="cb25-80"><a href="#cb25-80" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>bart <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-81"><a href="#cb25-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb25-82"><a href="#cb25-82" aria-hidden="true" tabindex="-1"></a>  <span class="fu">BARTLETT</span>()</span>
<span id="cb25-83"><a href="#cb25-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-84"><a href="#cb25-84" aria-hidden="true" tabindex="-1"></a><span class="co"># KMO-suure</span></span>
<span id="cb25-85"><a href="#cb25-85" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>kmosuure <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-86"><a href="#cb25-86" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb25-87"><a href="#cb25-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">KMO</span>()</span>
<span id="cb25-88"><a href="#cb25-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-89"><a href="#cb25-89" aria-hidden="true" tabindex="-1"></a><span class="co"># Korrelaatiomatriisin determinantti</span></span>
<span id="cb25-90"><a href="#cb25-90" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>determinantti <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-91"><a href="#cb25-91" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb25-92"><a href="#cb25-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-93"><a href="#cb25-93" aria-hidden="true" tabindex="-1"></a>  <span class="fu">det</span>()</span>
<span id="cb25-94"><a href="#cb25-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-95"><a href="#cb25-95" aria-hidden="true" tabindex="-1"></a><span class="co"># VIF-arvot</span></span>
<span id="cb25-96"><a href="#cb25-96" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>vif <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-97"><a href="#cb25-97" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb25-98"><a href="#cb25-98" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vif</span>()</span>
<span id="cb25-99"><a href="#cb25-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-100"><a href="#cb25-100" aria-hidden="true" tabindex="-1"></a><span class="co"># Hullin menetelmä</span></span>
<span id="cb25-101"><a href="#cb25-101" aria-hidden="true" tabindex="-1"></a>tulokset.efa.sopivuus<span class="sc">$</span>hull <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-102"><a href="#cb25-102" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb25-103"><a href="#cb25-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">HULL</span>(</span>
<span id="cb25-104"><a href="#cb25-104" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"ML"</span>,</span>
<span id="cb25-105"><a href="#cb25-105" aria-hidden="true" tabindex="-1"></a>    <span class="at">eigentype =</span> <span class="st">"SMC"</span>,</span>
<span id="cb25-106"><a href="#cb25-106" aria-hidden="true" tabindex="-1"></a>    <span class="at">decision_rule =</span> <span class="st">"percentile"</span></span>
<span id="cb25-107"><a href="#cb25-107" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-108"><a href="#cb25-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-109"><a href="#cb25-109" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-110"><a href="#cb25-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-111"><a href="#cb25-111" aria-hidden="true" tabindex="-1"></a>Mahalanobiksen etäisyyden merkitsevyystestaus (p <span class="sc">\&lt;</span> .001) osoittaa, että yhteensä <span class="in">`r tulokset.efa.sopivuus$poisto_n`</span> vastaajaa pitäisi poistaa mallista.</span>
<span id="cb25-112"><a href="#cb25-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-113"><a href="#cb25-113" aria-hidden="true" tabindex="-1"></a>KMO-suureen koko on <span class="in">`r tulokset.efa.sopivuus$kmosuure$KMO`</span>.</span>
<span id="cb25-114"><a href="#cb25-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-115"><a href="#cb25-115" aria-hidden="true" tabindex="-1"></a>Bartlettin testi on merkitsevä ($\chi^2 = <span class="in">`r tulokset.efa.sopivuus$bart$chisq`</span>, \text{df} = <span class="in">`r tulokset.efa.sopivuus$bart$df`</span>, p = <span class="in">`r tulokset.efa.sopivuus$bart$p_value`</span>$).</span>
<span id="cb25-116"><a href="#cb25-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-117"><a href="#cb25-117" aria-hidden="true" tabindex="-1"></a>Korrelaatiomatriisin determinantti on <span class="in">`r tulokset.efa.sopivuus$determinantti`</span>.</span>
<span id="cb25-118"><a href="#cb25-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-119"><a href="#cb25-119" aria-hidden="true" tabindex="-1"></a>Kaikki VIF-arvot ovat alle 10. Suurin VIF-arvo on $\text{VIF} = 4.8$ (<span class="in">`k29_11`</span>).</span>
<span id="cb25-120"><a href="#cb25-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-121"><a href="#cb25-121" aria-hidden="true" tabindex="-1"></a>Hullin menetelmän tulokset riippuvat käytetystä sopivuusindeksistä. CAF-indeksi ehdottaa <span class="in">`r tulokset.efa.sopivuus$hull$n_fac_CAF`</span> faktoria, CFI ehdottaa <span class="in">`r tulokset.efa.sopivuus$hull$n_fac_CFI`</span> faktoria ja RMSEA ehdottaa <span class="in">`r tulokset.efa.sopivuus$hull$n_fac_RMSEA`</span> faktoria.</span>
<span id="cb25-122"><a href="#cb25-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-123"><a href="#cb25-123" aria-hidden="true" tabindex="-1"></a><span class="fu">## EFA-mallien asettaminen</span></span>
<span id="cb25-124"><a href="#cb25-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-125"><a href="#cb25-125" aria-hidden="true" tabindex="-1"></a>Kokeilimme kahta mallia: Yhden faktorin mallia (A) ja neljän faktorin mallia (B). Jätimme analyysista pois kaikki Mahalanobiksen etäisyyden rajan rikkoneet vastaajat.</span>
<span id="cb25-126"><a href="#cb25-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-129"><a href="#cb25-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-130"><a href="#cb25-130" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tayvasenteet_validointi-03-datavalinta</span></span>
<span id="cb25-131"><a href="#cb25-131" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Mahalanobiksen etäisyyden rikkoneiden vastaajien poisjättäminen"</span></span>
<span id="cb25-132"><a href="#cb25-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-133"><a href="#cb25-133" aria-hidden="true" tabindex="-1"></a>data.valitut <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb25-134"><a href="#cb25-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mahalanobis.p <span class="sc">&gt;</span> .<span class="dv">001</span> <span class="sc">|</span> <span class="fu">is.na</span>(mahalanobis.p))</span>
<span id="cb25-135"><a href="#cb25-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-136"><a href="#cb25-136" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-137"><a href="#cb25-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-138"><a href="#cb25-138" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb25-139"><a href="#cb25-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-140"><a href="#cb25-140" aria-hidden="true" tabindex="-1"></a><span class="fu">### Malli A</span></span>
<span id="cb25-141"><a href="#cb25-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-144"><a href="#cb25-144" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-145"><a href="#cb25-145" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tayvasenteet_validointi-04-efamalli1</span></span>
<span id="cb25-146"><a href="#cb25-146" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "EFA-malli A"</span></span>
<span id="cb25-147"><a href="#cb25-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-148"><a href="#cb25-148" aria-hidden="true" tabindex="-1"></a>efa.malli.A <span class="ot">&lt;-</span> data.valitut <span class="sc">|&gt;</span></span>
<span id="cb25-149"><a href="#cb25-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb25-150"><a href="#cb25-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">efa</span>(</span>
<span id="cb25-151"><a href="#cb25-151" aria-hidden="true" tabindex="-1"></a>    <span class="at">nfactors =</span> <span class="dv">1</span>,</span>
<span id="cb25-152"><a href="#cb25-152" aria-hidden="true" tabindex="-1"></a>    <span class="at">rotation =</span> <span class="st">"oblimin"</span>,</span>
<span id="cb25-153"><a href="#cb25-153" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimator =</span> <span class="st">"ML"</span>,</span>
<span id="cb25-154"><a href="#cb25-154" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb25-155"><a href="#cb25-155" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-156"><a href="#cb25-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-157"><a href="#cb25-157" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.A <span class="ot">&lt;-</span> <span class="fu">summary</span>(</span>
<span id="cb25-158"><a href="#cb25-158" aria-hidden="true" tabindex="-1"></a>  efa.malli.A,</span>
<span id="cb25-159"><a href="#cb25-159" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-160"><a href="#cb25-160" aria-hidden="true" tabindex="-1"></a>  <span class="at">ci =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-161"><a href="#cb25-161" aria-hidden="true" tabindex="-1"></a>  <span class="at">efa =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-162"><a href="#cb25-162" aria-hidden="true" tabindex="-1"></a>  <span class="at">cutoff =</span> <span class="dv">0</span></span>
<span id="cb25-163"><a href="#cb25-163" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-164"><a href="#cb25-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-165"><a href="#cb25-165" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.A</span>
<span id="cb25-166"><a href="#cb25-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-167"><a href="#cb25-167" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-168"><a href="#cb25-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-169"><a href="#cb25-169" aria-hidden="true" tabindex="-1"></a><span class="fu">### Malli B</span></span>
<span id="cb25-170"><a href="#cb25-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-173"><a href="#cb25-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-174"><a href="#cb25-174" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tayvasenteet_validointi-05-efamalli2</span></span>
<span id="cb25-175"><a href="#cb25-175" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "EFA-malli B"</span></span>
<span id="cb25-176"><a href="#cb25-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-177"><a href="#cb25-177" aria-hidden="true" tabindex="-1"></a>efa.malli.B <span class="ot">&lt;-</span> data.valitut <span class="sc">|&gt;</span></span>
<span id="cb25-178"><a href="#cb25-178" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(k29_1<span class="sc">:</span>k29_12) <span class="sc">|&gt;</span></span>
<span id="cb25-179"><a href="#cb25-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">efa</span>(</span>
<span id="cb25-180"><a href="#cb25-180" aria-hidden="true" tabindex="-1"></a>    <span class="at">nfactors =</span> <span class="dv">4</span>,</span>
<span id="cb25-181"><a href="#cb25-181" aria-hidden="true" tabindex="-1"></a>    <span class="at">rotation =</span> <span class="st">"oblimin"</span>,</span>
<span id="cb25-182"><a href="#cb25-182" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimator =</span> <span class="st">"ML"</span>,</span>
<span id="cb25-183"><a href="#cb25-183" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb25-184"><a href="#cb25-184" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-185"><a href="#cb25-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-186"><a href="#cb25-186" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.B <span class="ot">&lt;-</span> <span class="fu">summary</span>(</span>
<span id="cb25-187"><a href="#cb25-187" aria-hidden="true" tabindex="-1"></a>  efa.malli.B,</span>
<span id="cb25-188"><a href="#cb25-188" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-189"><a href="#cb25-189" aria-hidden="true" tabindex="-1"></a>  <span class="at">ci =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-190"><a href="#cb25-190" aria-hidden="true" tabindex="-1"></a>  <span class="at">efa =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-191"><a href="#cb25-191" aria-hidden="true" tabindex="-1"></a>  <span class="at">cutoff =</span> <span class="dv">0</span></span>
<span id="cb25-192"><a href="#cb25-192" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-193"><a href="#cb25-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-194"><a href="#cb25-194" aria-hidden="true" tabindex="-1"></a>yhteenveto.efa.B</span>
<span id="cb25-195"><a href="#cb25-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-196"><a href="#cb25-196" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-197"><a href="#cb25-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-198"><a href="#cb25-198" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb25-199"><a href="#cb25-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-200"><a href="#cb25-200" aria-hidden="true" tabindex="-1"></a>Molemmat mallit sopivat huonosti. Malli A:n sopivuusarvot ovat: $\text{RMSEA} = 0.213, \text{CFI} = .758$. Malli B:n sopivuusarvot ovat: $\text{RMSEA} = 0.141, \text{CFI} = .980$. AIC- ja BIC-arvot paranevat jonkin verran Malli B:ssä, mutta eivät suuresti.</span>
<span id="cb25-201"><a href="#cb25-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-202"><a href="#cb25-202" aria-hidden="true" tabindex="-1"></a>Malli A kattaa yhteensä 56,4 prosenttia varianssista. Malli B kattaa 74,7 prosenttia varianssista.</span>
<span id="cb25-203"><a href="#cb25-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-204"><a href="#cb25-204" aria-hidden="true" tabindex="-1"></a>Malli A:ssa kaikki muuttujat lataavat merkitsevästi positiivisesti faktoriin. Lataukset ovat suhteellisen samankokoisia ($0.637-0.888$).</span>
<span id="cb25-205"><a href="#cb25-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-206"><a href="#cb25-206" aria-hidden="true" tabindex="-1"></a>Malli B:ssä kaikki muuttujat paitsi <span class="in">`k29_2`</span> lataavat merkitsevästi vähintään yhteen faktoriin. Lataukset ovat kuitenkin erisuuntaisia:</span>
<span id="cb25-207"><a href="#cb25-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-208"><a href="#cb25-208" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttuja <span class="in">`k29_1`</span> lataa positiivisesti faktoreihin <span class="in">`f1`</span>, <span class="in">`f2`</span> ja <span class="in">`f4`</span>, joista suurin lataus on viimeisellä faktorilla.</span>
<span id="cb25-209"><a href="#cb25-209" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttuja <span class="in">`k29_3`</span> lataa positiivisesti faktoriin <span class="in">`f2`</span>, eikä lataa muihin faktoreihin merkitsevästi.</span>
<span id="cb25-210"><a href="#cb25-210" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttuja <span class="in">`k29_4`</span> lataa positiivisesti faktoreihin <span class="in">`f1`</span> ja <span class="in">`f2`</span>.</span>
<span id="cb25-211"><a href="#cb25-211" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttuja <span class="in">`k29_5`</span> lataa positiivisesti faktoriin <span class="in">`f2`</span> ja negatiivisesti faktoriin <span class="in">`f1`</span></span>
<span id="cb25-212"><a href="#cb25-212" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttujat <span class="in">`k29_6`</span> sekä <span class="in">`k29_9`</span> lataavat positiivisesti faktoriin <span class="in">`f3`</span>, eivätkä lataa muihin faktoreihin merkitsevästi.</span>
<span id="cb25-213"><a href="#cb25-213" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttuja <span class="in">`k29_7`</span> lataa positiivisesti faktoriin <span class="in">`f3`</span> ja negatiivisesti faktoriin <span class="in">`f4`</span>.</span>
<span id="cb25-214"><a href="#cb25-214" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttujat <span class="in">`k29_8`</span> sekä <span class="in">`k29_10`</span> lataavat positiivisesti faktoreihin <span class="in">`f3`</span> ja <span class="in">`f4`</span>.</span>
<span id="cb25-215"><a href="#cb25-215" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttuja <span class="in">`k29_11`</span> lataa positiivisesti faktoriin <span class="in">`f4`</span>, eikä lataa muihin faktoreihin merkitsevästi.</span>
<span id="cb25-216"><a href="#cb25-216" aria-hidden="true" tabindex="-1"></a><span class="ss">-  </span>Muuttuja <span class="in">`k29_12`</span> lataa positiivisesti faktoreihin <span class="in">`f2`</span> ja <span class="in">`f4`</span>.</span>
<span id="cb25-217"><a href="#cb25-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-218"><a href="#cb25-218" aria-hidden="true" tabindex="-1"></a>Faktorit <span class="in">`f2-f4`</span> edustavat suhteellisen suuria varianssiosuuksia ($18.3-30.8 \%$). Faktori <span class="in">`f1`</span> edustaa pienempää $5.1 \%$ varianssista.</span>
<span id="cb25-219"><a href="#cb25-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-220"><a href="#cb25-220" aria-hidden="true" tabindex="-1"></a>Kaikki faktorit korreloivat positiivisesti toistensa kanssa, mutta faktorin <span class="in">`f1`</span> korrelaatiot eivät ole merkitseviä 1 prosentin tasolla.</span>
<span id="cb25-221"><a href="#cb25-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-222"><a href="#cb25-222" aria-hidden="true" tabindex="-1"></a>Faktori <span class="in">`f1`</span> näyttäisi olevan tilastollinen artefakti: faktorille ei löydy selkeää tulkintaa, siihen lataa vain harva muuttuja, ja se kattaa vain pienen osan kaikesta vaihtelusta.</span>
<span id="cb25-223"><a href="#cb25-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-224"><a href="#cb25-224" aria-hidden="true" tabindex="-1"></a>Faktori <span class="in">`f2`</span> näyttäisi liittyvän turvallisen henkilöstön valintoihin. Siihen lataa suuresti turvallisuusselvitykset, alaikäisten koskettomattomuuden turvaaminen sekä rikostaustojen tarkistaminen.</span>
<span id="cb25-225"><a href="#cb25-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-226"><a href="#cb25-226" aria-hidden="true" tabindex="-1"></a>Faktori <span class="in">`f3`</span> näyttäisi liittyvän organisaatiotukeen epäasiallisen ja väkivaltaisen kohtelun kokemuksissa. Siihen lataa suuresti erilaiset toiminta- ja jatkotoimiohjeet kohtelutilanteissa sekä kohtelun raportointijärjestelmät.</span>
<span id="cb25-227"><a href="#cb25-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-228"><a href="#cb25-228" aria-hidden="true" tabindex="-1"></a>Faktori <span class="in">`f4`</span> näytäisi liittyvän tasa-arvoon ja yhdenvertaisuuteen tähtääviin toimenpiteisiin. Siihen lataa selkeimmin keskustelu- ja infotilaisuudet yhdenvertaisuuteen liittyen, mutta myös pienemmissä määrin koulutus sekä ilmoitusjärjestelmät.</span>
<span id="cb25-229"><a href="#cb25-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-230"><a href="#cb25-230" aria-hidden="true" tabindex="-1"></a><span class="fu">## CFA-mallien asettamista</span></span>
<span id="cb25-231"><a href="#cb25-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-232"><a href="#cb25-232" aria-hidden="true" tabindex="-1"></a>Aloitimme asettamalla kaksi CFA-mallia, peilaten tuloksia EFA-malleista A ja B.</span>
<span id="cb25-233"><a href="#cb25-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-236"><a href="#cb25-236" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-237"><a href="#cb25-237" aria-hidden="true" tabindex="-1"></a>cfa.malli.A <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb25-238"><a href="#cb25-238" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb25-239"><a href="#cb25-239" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_1 + k29_3 + k29_4 + k29_5 + k29_6 + k29_7 + k29_8 + k29_9 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb25-240"><a href="#cb25-240" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb25-241"><a href="#cb25-241" aria-hidden="true" tabindex="-1"></a>malli.A <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb25-242"><a href="#cb25-242" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.A,</span>
<span id="cb25-243"><a href="#cb25-243" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_12),</span>
<span id="cb25-244"><a href="#cb25-244" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb25-245"><a href="#cb25-245" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb25-246"><a href="#cb25-246" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-247"><a href="#cb25-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-248"><a href="#cb25-248" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.A, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-249"><a href="#cb25-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-250"><a href="#cb25-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-251"><a href="#cb25-251" aria-hidden="true" tabindex="-1"></a>Malli A sopii hyvin huonosti aineistoon. Robusti RMSEA on $0.224$ ja robusti CFI on $0.748$, mitkä ovat molemmat reilusti yleisesti hyväksyttävien raja-arvojen ulkopuolella. Robusti SRMR on hieman parempi $0.086$, joskin sekin raja-arvon ulkopuolella.</span>
<span id="cb25-252"><a href="#cb25-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-255"><a href="#cb25-255" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-256"><a href="#cb25-256" aria-hidden="true" tabindex="-1"></a>cfa.malli.B <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb25-257"><a href="#cb25-257" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb25-258"><a href="#cb25-258" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_3 + k29_4 + k29_5</span></span>
<span id="cb25-259"><a href="#cb25-259" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 =~ k29_6 + k29_7 + k29_8 + k29_9 + k29_10</span></span>
<span id="cb25-260"><a href="#cb25-260" aria-hidden="true" tabindex="-1"></a><span class="st">              f3 =~ k29_1 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb25-261"><a href="#cb25-261" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb25-262"><a href="#cb25-262" aria-hidden="true" tabindex="-1"></a><span class="st">              # faktorikorrelaatiot</span></span>
<span id="cb25-263"><a href="#cb25-263" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f2</span></span>
<span id="cb25-264"><a href="#cb25-264" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 ~~ f3</span></span>
<span id="cb25-265"><a href="#cb25-265" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f3</span></span>
<span id="cb25-266"><a href="#cb25-266" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb25-267"><a href="#cb25-267" aria-hidden="true" tabindex="-1"></a>malli.B <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb25-268"><a href="#cb25-268" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.B,</span>
<span id="cb25-269"><a href="#cb25-269" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_12),</span>
<span id="cb25-270"><a href="#cb25-270" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb25-271"><a href="#cb25-271" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb25-272"><a href="#cb25-272" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-273"><a href="#cb25-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-274"><a href="#cb25-274" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.B, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-275"><a href="#cb25-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-276"><a href="#cb25-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-277"><a href="#cb25-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-278"><a href="#cb25-278" aria-hidden="true" tabindex="-1"></a>Malli B sopii jossain määrin aineistoon. Robusti RMSEA on $0.104$, mikä on raja-arvon ulkopuolella. Robusti CFI on $0.950$, mikä on juuri raja-arvolla. Robusti SRMR on $.044$, mikä on hyväksyttävissä rajoissa.</span>
<span id="cb25-279"><a href="#cb25-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-282"><a href="#cb25-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-283"><a href="#cb25-283" aria-hidden="true" tabindex="-1"></a>vrt <span class="ot">&lt;-</span> <span class="fu">compareFit</span>(</span>
<span id="cb25-284"><a href="#cb25-284" aria-hidden="true" tabindex="-1"></a>  malli.B,</span>
<span id="cb25-285"><a href="#cb25-285" aria-hidden="true" tabindex="-1"></a>  malli.A,</span>
<span id="cb25-286"><a href="#cb25-286" aria-hidden="true" tabindex="-1"></a>  <span class="at">nested =</span> <span class="cn">FALSE</span>,</span>
<span id="cb25-287"><a href="#cb25-287" aria-hidden="true" tabindex="-1"></a>  <span class="at">moreIndices =</span> <span class="cn">TRUE</span></span>
<span id="cb25-288"><a href="#cb25-288" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-289"><a href="#cb25-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-290"><a href="#cb25-290" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vrt)</span>
<span id="cb25-291"><a href="#cb25-291" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-292"><a href="#cb25-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-293"><a href="#cb25-293" aria-hidden="true" tabindex="-1"></a>Mallien vertailu osoittaa selkeästi, että Malli B sopii aineistoon paremmin kaikilla mittareilla.</span>
<span id="cb25-294"><a href="#cb25-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-297"><a href="#cb25-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-298"><a href="#cb25-298" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(malli.B) <span class="sc">|&gt;</span></span>
<span id="cb25-299"><a href="#cb25-299" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mi)) <span class="sc">|&gt;</span></span>
<span id="cb25-300"><a href="#cb25-300" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(op <span class="sc">==</span> <span class="st">"=~"</span>)</span>
<span id="cb25-301"><a href="#cb25-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-302"><a href="#cb25-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-303"><a href="#cb25-303" aria-hidden="true" tabindex="-1"></a>Malli B:ssä suurimmat indeksimuutokset koskevat muuttujaa <span class="in">`k29_1`</span>. Sen vapauttaminen kaikille faktoreille aiheuttaisi $50.7$ (<span class="in">`f1`</span>) ja $30.5$ (<span class="in">`f2`</span>) laskun khii neliö -indeksissä. Odotetut faktorilatausarvot pieniä ovat $\text{F1} = .247, \text{F2} = .212$.</span>
<span id="cb25-304"><a href="#cb25-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-307"><a href="#cb25-307" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-308"><a href="#cb25-308" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(malli.B) <span class="sc">|&gt;</span></span>
<span id="cb25-309"><a href="#cb25-309" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mi)) <span class="sc">|&gt;</span></span>
<span id="cb25-310"><a href="#cb25-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(op <span class="sc">==</span> <span class="st">"~~"</span>)</span>
<span id="cb25-311"><a href="#cb25-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-312"><a href="#cb25-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-313"><a href="#cb25-313" aria-hidden="true" tabindex="-1"></a>Virhekorrelaatioiden modifikaatioindeksit osoittavat kuitenkin suurempia ongelmia. Suurimmat modifikaatioindeksit löytyvät pääsääntöisesti faktorin <span class="in">`f2`</span> muuttujilta <span class="in">`k29_6`</span>, <span class="in">`k29_7`</span>, <span class="in">`k29_9`</span> ja <span class="in">`k29_10`</span>. Varsinkin muuttujien <span class="in">`k29_9`</span> ja <span class="in">`k29_10`</span> virheen vapauttaminen antaisi odotetusti jopa korrelaation <span class="in">`0.922`</span>, eli erittäin suuren korrelaation.</span>
<span id="cb25-314"><a href="#cb25-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-315"><a href="#cb25-315" aria-hidden="true" tabindex="-1"></a>Onkin huomattava, että muuttuja <span class="in">`k29_8`</span> *ei* nouse suurimpien modifikaatioindeksien ryhmään. Tämä voisi osoittaa, että muuttuja käytännössä kaappaa faktorivarianssin, jolloin muut muuttujat eivät pääse lataamaan vapaasti faktoriin <span class="in">`f2`</span>.</span>
<span id="cb25-316"><a href="#cb25-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-317"><a href="#cb25-317" aria-hidden="true" tabindex="-1"></a>Kokeilimme siksi mallia, jossa jätimme pois muuttujan <span class="in">`k29_8`</span> kokonaan (Malli C).</span>
<span id="cb25-318"><a href="#cb25-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-321"><a href="#cb25-321" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-322"><a href="#cb25-322" aria-hidden="true" tabindex="-1"></a>cfa.malli.C <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb25-323"><a href="#cb25-323" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb25-324"><a href="#cb25-324" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_3 + k29_4 + k29_5</span></span>
<span id="cb25-325"><a href="#cb25-325" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 =~ k29_6 + k29_7 + k29_9 + k29_10</span></span>
<span id="cb25-326"><a href="#cb25-326" aria-hidden="true" tabindex="-1"></a><span class="st">              f3 =~ k29_1 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb25-327"><a href="#cb25-327" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb25-328"><a href="#cb25-328" aria-hidden="true" tabindex="-1"></a><span class="st">              # faktorikorrelaatiot</span></span>
<span id="cb25-329"><a href="#cb25-329" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f2</span></span>
<span id="cb25-330"><a href="#cb25-330" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 ~~ f3</span></span>
<span id="cb25-331"><a href="#cb25-331" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f3</span></span>
<span id="cb25-332"><a href="#cb25-332" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb25-333"><a href="#cb25-333" aria-hidden="true" tabindex="-1"></a>malli.C <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb25-334"><a href="#cb25-334" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.C,</span>
<span id="cb25-335"><a href="#cb25-335" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_7, k29_9<span class="sc">:</span>k29_12),</span>
<span id="cb25-336"><a href="#cb25-336" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb25-337"><a href="#cb25-337" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb25-338"><a href="#cb25-338" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-339"><a href="#cb25-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-340"><a href="#cb25-340" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.C, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-341"><a href="#cb25-341" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-342"><a href="#cb25-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-343"><a href="#cb25-343" aria-hidden="true" tabindex="-1"></a>Mallin sopivuusarvot eivät muutu juuri ollenkaan. Robusti RMSEA on nyt lievästi heikompi $0.111$, CFI on vielä $0.950$ ja SRMR on hivenen heikompi $0.045$. Toisin sanoen, malli ei näytä parantuvan jättämällä muuttujan <span class="in">`k29_8`</span> pois analyysista.</span>
<span id="cb25-344"><a href="#cb25-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-347"><a href="#cb25-347" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-348"><a href="#cb25-348" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(malli.C) <span class="sc">|&gt;</span></span>
<span id="cb25-349"><a href="#cb25-349" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mi)) <span class="sc">|&gt;</span></span>
<span id="cb25-350"><a href="#cb25-350" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(op <span class="sc">==</span> <span class="st">"~~"</span>)</span>
<span id="cb25-351"><a href="#cb25-351" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-352"><a href="#cb25-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-353"><a href="#cb25-353" aria-hidden="true" tabindex="-1"></a>Kokeilimme palauttaa muuttujan <span class="in">`k29_8`</span> malliin ja vapauttamaan virhekorrelaatiot muuttujapareille <span class="in">`k29_6-k29_9`</span>, <span class="in">`k29_9-k29_10`</span> sekä <span class="in">`k29_7-k29_10`</span> (Malli D).</span>
<span id="cb25-354"><a href="#cb25-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-357"><a href="#cb25-357" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb25-358"><a href="#cb25-358" aria-hidden="true" tabindex="-1"></a>cfa.malli.D <span class="ot">&lt;-</span>  <span class="st">'</span></span>
<span id="cb25-359"><a href="#cb25-359" aria-hidden="true" tabindex="-1"></a><span class="st">              # latentit muuttujat</span></span>
<span id="cb25-360"><a href="#cb25-360" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 =~ k29_3 + k29_4 + k29_5</span></span>
<span id="cb25-361"><a href="#cb25-361" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 =~ k29_6 + k29_7 + k29_8 + k29_9 + k29_10</span></span>
<span id="cb25-362"><a href="#cb25-362" aria-hidden="true" tabindex="-1"></a><span class="st">              f3 =~ k29_1 + k29_10 + k29_11 + k29_12</span></span>
<span id="cb25-363"><a href="#cb25-363" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb25-364"><a href="#cb25-364" aria-hidden="true" tabindex="-1"></a><span class="st">              # faktorikorrelaatiot</span></span>
<span id="cb25-365"><a href="#cb25-365" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f2</span></span>
<span id="cb25-366"><a href="#cb25-366" aria-hidden="true" tabindex="-1"></a><span class="st">              f2 ~~ f3</span></span>
<span id="cb25-367"><a href="#cb25-367" aria-hidden="true" tabindex="-1"></a><span class="st">              f1 ~~ f3</span></span>
<span id="cb25-368"><a href="#cb25-368" aria-hidden="true" tabindex="-1"></a><span class="st">              </span></span>
<span id="cb25-369"><a href="#cb25-369" aria-hidden="true" tabindex="-1"></a><span class="st">              # virhekorrelaatiot</span></span>
<span id="cb25-370"><a href="#cb25-370" aria-hidden="true" tabindex="-1"></a><span class="st">              k29_6 ~~ k29_9</span></span>
<span id="cb25-371"><a href="#cb25-371" aria-hidden="true" tabindex="-1"></a><span class="st">              k29_9 ~~ k29_10</span></span>
<span id="cb25-372"><a href="#cb25-372" aria-hidden="true" tabindex="-1"></a><span class="st">              k29_7 ~~ k29_10</span></span>
<span id="cb25-373"><a href="#cb25-373" aria-hidden="true" tabindex="-1"></a><span class="st">              '</span></span>
<span id="cb25-374"><a href="#cb25-374" aria-hidden="true" tabindex="-1"></a>malli.D <span class="ot">&lt;-</span> <span class="fu">cfa</span>(</span>
<span id="cb25-375"><a href="#cb25-375" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> cfa.malli.D,</span>
<span id="cb25-376"><a href="#cb25-376" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data.valitut <span class="sc">|&gt;</span> <span class="fu">select</span>(k29_1, k29_3<span class="sc">:</span>k29_12),</span>
<span id="cb25-377"><a href="#cb25-377" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb25-378"><a href="#cb25-378" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb25-379"><a href="#cb25-379" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-380"><a href="#cb25-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-381"><a href="#cb25-381" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(malli.D, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-382"><a href="#cb25-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb25-383"><a href="#cb25-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-384"><a href="#cb25-384" aria-hidden="true" tabindex="-1"></a>Malli D sopii mallia B lievästi paremmin. Robusti RMSEA on nyt parantunut tasolle $0.082$, CFI on parantunut tasolle $0.972$ ja SRMR on kuta kuinkin samalla tasolla, $0.042$. Malli ei kuitenkaan vieläkään sovi kaikkien raja-arvojen sisällä.</span>
<span id="cb25-385"><a href="#cb25-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-386"><a href="#cb25-386" aria-hidden="true" tabindex="-1"></a>Totesimme tässä vaiheessa, ettemme pysty asettamaan raja-arvojen mukaista mallia, ja hylkäsimme kaikki mallit.</span>
<span id="cb25-387"><a href="#cb25-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-388"><a href="#cb25-388" aria-hidden="true" tabindex="-1"></a><span class="fu">## Yhteenveto</span></span>
<span id="cb25-389"><a href="#cb25-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-390"><a href="#cb25-390" aria-hidden="true" tabindex="-1"></a>Emme pystyneet asettamaan mallia, joka sopisi yleisesti hyväksyttyjen raja-arvojen puitteissa kaikilla indekseillä. Parhaiten sopiva malli on Malli D: kolmen faktorin malli, jossa kolme virhekorrelaatiota on vapautettu muuttujien <span class="in">`k29_6`</span> (Ohjeet ahdistelutilanteiden käsittelyyn), <span class="in">`k29_7`</span> (Ohjeet uhka- ja väkivaltatilanteen käsittelyyn), <span class="in">`k29_9`</span> (Koulutus väkivaltatilanteiden kohtaamiselle) ja <span class="in">`k29_10`</span> (Koulutus kohtelun tunnistamiselle) välillä.</span>
<span id="cb25-391"><a href="#cb25-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-392"><a href="#cb25-392" aria-hidden="true" tabindex="-1"></a>Mallin epäsopivuudelle voi olla useita eri selityksiä. On mahdollista, että sovitamme väärää mallia aineistoon, ja että asenteet riippuvat todellisuudessa muista syistä. On myös mahdollista, että otantamme ei pysty tunnistamaan mallia vääristymien takia, tai että meiltä puuttuu jotain muuttujia, jotka paremmin kuvailisivat latentteja asennefaktoreita. Aineistossa voi myös olla vastaajia, joiden vastauskonfiguraatiot aiheuttavat joko vääriä positiiveja tai negatiiveja.</span>
<span id="cb25-393"><a href="#cb25-393" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Kopioi leikepöydälle" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>